import {describe,it,expect} from 'vitest';
import {canonicalSha256} from '../../rule-runtime/canonical.ts';
import {travelEntitlementInputSchema,type TravelEntitlementInput} from './contracts.ts';
import {travelProductFacts,travelProductFactQuestions,travelProductRoute,evaluateTravelCaseRecipe,travelCaseConsumed,travelCaseBinding,replayTravelProductFacts} from './product-facts.ts';
import {resolveTravelEntitlement,TRAVEL_APPLICABILITY,travelLegalSource} from './index.ts';
import {calculateDocumentReview,type DocumentReviewOperand} from '../../document-review/calculations.ts';
import {documentReviewInputSchema} from '../../document-review/contracts.ts';
import {AI_RELEASE_DECISION_RECIPES} from '../../ai-release-decisions/catalog.ts';

const sha='e'.repeat(64),source={document_id:'synthetic-tariff-source',version_id:'synthetic-tariff-v1',file_sha256:sha,page:1,locator:'Synthetic explicitly associated route tariff table',label:'Synthetic source only',reading:'identified_document_reading' as const,reading_receipt_sha256:sha};
const observed=(value:unknown)=>({state:'observed',value,source}),known=(value:unknown)=>({state:'known',value,source,basis:'identified_document_reading'});
const money=(id:string,value:string):DocumentReviewOperand=>({id,observation_id:'synthetic.'+id,state:'observed',printed_value:value,representation:'money_ils',quantity_unit:null,precision:'printed_precision',source:{...source,locator:'Synthetic tariff table cell '+id}});
function fixture():TravelEntitlementInput{
 const daily=money('daily','12.00'),monthly=money('monthly','200.00');
 return travelEntitlementInputSchema.parse({schema_version:'travel-entitlement-input-v1',catalog_id:'il.review.travel.general.2026',catalog_version:'1.0.0',case_id:'synthetic-case',run_id:'synthetic-run',check_prefix:'synthetic.travel',period:{from:'2026-06-01',to:'2026-06-30'},evaluated_at:'2026-09-10T00:00:00Z',
  source_manifest:[{document_id:source.document_id,version_id:source.version_id,file_sha256:sha,page_count:2,kind:'case_document',case_id:'synthetic-case'}],
  facts:{needs_transport:known(true),employer_transport:known('none'),free_travel:known('none')},commute_days:{...money('days','20'),representation:'decimal_quantity',quantity_unit:'days'},discounted_daily_fare:daily,monthly_pass:known('available'),monthly_pass_cost:monthly,recorded:null,applicability:[],
  product_facts:{...travelProductFacts(),employment_relationship:observed('employee'),workplace_sector:observed('private'),route_reference:observed('Synthetic route A'),personal_discount_profile:observed('standard_adult')},
  fare_source_context:{schema_version:'travel-fare-source-context-v1',route_reference:observed('Synthetic route A'),discount_profile:observed('standard_adult'),association:observed('same_route_tariff_group'),effective_period:observed({from:'2026-05-01',to:'2026-07-31'}),directions:observed('both'),ticket_inventory:observed('complete'),monthly_pass_availability:observed('available'),daily_fare_operand_sha256:canonicalSha256(daily),monthly_pass_operand_sha256:canonicalSha256(monthly)},remittance_status:'missing'});
}
function review(i:TravelEntitlementInput){return documentReviewInputSchema.parse({schema_version:'document-review-product-v1',case_id:i.case_id,period:i.period,purchased_scope:{order_id:'synthetic-order',receipt_sha256:sha,origin:'saved_order',topics:['travel']},documents:[{case_id:i.case_id,document_id:source.document_id,version_id:source.version_id,file_sha256:sha,reading_sha256:sha,page_count:2,kind:'other',label:'Synthetic tariff table',period:i.period,reading_origin:'identified_document_reading'}],checks:[],completion_input:{},answer_history:[],answer_bindings:[],coverage_gaps:[]});}
function bind(i:TravelEntitlementInput,id='travel.general_coverage'){
 const recipe=AI_RELEASE_DECISION_RECIPES.find(r=>r.recipe_id==='ai-case.'+id);if(!recipe)throw Error('Synthetic test requires compiled travel case recipe');
 const method={recipe_id:recipe.recipe_id,recipe_version:recipe.recipe_version,recipe_sha256:recipe.recipe_sha256,source_policy_sha256:recipe.source_policy_sha256,interpretation_receipt_sha256:sha,source_receipts:recipe.legal_sources.map(s=>({receipt_sha256:sha,source_version_id:s.version_id,artifact_sha256:s.file_sha256})),issued_at:'2026-09-11T00:00:00Z',expires_at:'2026-09-14T00:00:00Z'};
 const binding=travelCaseBinding(method,'2026-09-12T00:00:00Z'),paths=evaluateTravelCaseRecipe(id,i).consumed_paths;
 return travelEntitlementInputSchema.parse({...i,case_recipe_bindings:[binding],applicability:[{decision_id:id,state:'accepted',basis:'ai_source_assessment',sources:recipe.legal_sources,valid_until:method.expires_at,explanation:JSON.stringify({schema_version:'ai-release-method-basis-v1',recipe_id:recipe.recipe_id,recipe_sha256:recipe.recipe_sha256,interpretation_receipt_sha256:sha,consumed_sha256:canonicalSha256(travelCaseConsumed(i,paths))})}]});
}
describe('travel sourced factual recipes without new fare arithmetic',()=>{
 it('leaves absent opt-in fields and historical bytes absent',()=>{const i=fixture();delete i.product_facts;delete i.fare_source_context;expect(travelEntitlementInputSchema.parse(i)).toEqual(i);expect(travelProductFactQuestions(i)).toEqual([]);expect(replayTravelProductFacts(i,i)).toEqual(i);});
 it('does not repeat existing source amounts, route facts or already answered employment fields',()=>{expect(travelProductFactQuestions(fixture()).map(q=>q.path)).toEqual(['product_facts.other_travel_terms_known']);});
 it.each(['no_need','employer_both','free_both','no_uncovered_direction','no_commute_days'] as const)('keeps the %s zero route independent of unknown price and discount evidence',branch=>{
  const i=fixture();delete i.fare_source_context;i.discounted_daily_fare=null;i.monthly_pass_cost=null;i.monthly_pass={state:'unknown',value:null,source:null,basis:'ai_source_assessment'};i.product_facts!.personal_discount_profile={state:'unknown',value:null,source:null};i.product_facts!.route_reference={state:'unknown',value:null,source:null};
  if(branch==='no_need')i.facts.needs_transport.value=false;if(branch==='employer_both')i.facts.employer_transport.value='both';if(branch==='free_both')i.facts.free_travel.value='both';if(branch==='no_uncovered_direction'){i.facts.employer_transport.value='outbound';i.facts.free_travel.value='return';}if(branch==='no_commute_days')i.commute_days!.printed_value='0';
  expect(travelProductRoute(i)).toMatchObject({kind:'zero',reason:branch});expect(evaluateTravelCaseRecipe('travel.general_coverage',i)).toMatchObject({allowed:true});expect(evaluateTravelCaseRecipe('travel.fare_basis',i)).toMatchObject({allowed:false,reason:'fare_recipe_not_consumed_by_zero_branch'});
  expect(travelProductFactQuestions(i).some(q=>q.path.endsWith('route_reference')||q.path.endsWith('personal_discount_profile'))).toBe(false);
  i.applicability=['travel.general_coverage','travel.no_better_arrangement'].map(decision_id=>({decision_id,state:'accepted',basis:'ai_source_assessment',explanation:'Synthetic independent source assessment',sources:[travelLegalSource(1,decision_id)],valid_until:null}));
  expect(calculateDocumentReview(resolveTravelEntitlement(i).checks[0].calculation)).toMatchObject({state:'calculated',expected:{minor_units:0}});
 });
 it.each(['missing','unknown','conflict','stale','expired','unreadable'] as const)('preserves %s product facts instead of accepting population scope',state=>{const i=fixture();i.product_facts!.employment_relationship={state,value:null,source:null};expect(evaluateTravelCaseRecipe('travel.general_coverage',i)).toMatchObject({allowed:false,reason:'employment_scope_missing'});});
 it('excludes a protected workshop and requires dated treatment for mixed directions',()=>{const i=fixture();i.product_facts!.workplace_sector.value='protected_workshop';expect(evaluateTravelCaseRecipe('travel.general_coverage',i)).toMatchObject({allowed:false,reason:'unsupported_employment_scope'});i.product_facts!.workplace_sector.value='private';i.facts.employer_transport.value='mixed';expect(evaluateTravelCaseRecipe('travel.general_coverage',i)).toMatchObject({allowed:false,reason:'dated_direction_breakdown_required'});});
 it('accepts exact identified tariff context and computes with the retained RuleSpec formula',()=>{const i=fixture();for(const id of ['travel.general_coverage','travel.fare_basis','travel.ticket_options'])expect(evaluateTravelCaseRecipe(id,i,review(i))).toMatchObject({allowed:true});
  i.applicability=Object.keys(TRAVEL_APPLICABILITY).map(decision_id=>({decision_id,state:'accepted',basis:'ai_source_assessment',explanation:'Synthetic source-reviewed conditions, not a live approval',sources:[travelLegalSource(1,decision_id)],valid_until:null}));expect(calculateDocumentReview(resolveTravelEntitlement(i).checks[0].calculation)).toMatchObject({state:'calculated',expected:{minor_units:20000}});
 });
 it('does not treat a declared fare as a verified source cell',()=>{const i=fixture();i.discounted_daily_fare!.state='declared';i.fare_source_context!.daily_fare_operand_sha256=canonicalSha256(i.discounted_daily_fare);expect(evaluateTravelCaseRecipe('travel.fare_basis',i)).toMatchObject({allowed:false,reason:'identified_daily_fare_cell_required'});});
 it('requires an identified association rather than matching source numbers or labels',()=>{const i=fixture();i.fare_source_context!.association={state:'unknown',value:null,source:null};expect(evaluateTravelCaseRecipe('travel.fare_basis',i)).toMatchObject({allowed:false,reason:'identified_association_required'});});
 it('blocks stale tariff periods, unmatched directions, personal profiles and group pages',()=>{
  const variants:[(i:TravelEntitlementInput)=>void,string][]=[
   [i=>{i.fare_source_context!.effective_period.value={from:'2026-05-01',to:'2026-05-31'};},'fare_effective_period_mismatch'],
   [i=>{i.fare_source_context!.directions.value='return';},'fare_directions_mismatch'],
   [i=>{i.product_facts!.personal_discount_profile.value='special_discount';},'special_discount_applicability_source_required'],
   [i=>{i.fare_source_context!.route_reference.source={...source,page:2};},'fare_group_source_mismatch'],
   [i=>{i.product_facts!.route_reference.value='Different route';},'declared_route_source_conflict'],
   [i=>{i.discounted_daily_fare!.printed_value='13.00';},'identified_daily_fare_cell_required'],
  ];for(const [change,reason]of variants){const i=fixture();change(i);expect(evaluateTravelCaseRecipe('travel.fare_basis',i)).toMatchObject({allowed:false,reason});}
 });
 it('requires complete ticket inventory and source-backed availability, not a missing pass price',()=>{const i=fixture();i.fare_source_context!.ticket_inventory.value='partial';expect(evaluateTravelCaseRecipe('travel.ticket_options',i)).toMatchObject({allowed:false,reason:'complete_discounted_ticket_inventory_required'});i.fare_source_context!.ticket_inventory.value='complete';i.monthly_pass_cost=null;expect(evaluateTravelCaseRecipe('travel.ticket_options',i)).toMatchObject({allowed:false,reason:'identified_monthly_pass_cell_required'});i.monthly_pass.value='unavailable';expect(evaluateTravelCaseRecipe('travel.ticket_options',i)).toMatchObject({allowed:false,reason:'monthly_pass_availability_source_required'});i.fare_source_context!.monthly_pass_availability.value='unavailable';i.fare_source_context!.monthly_pass_operand_sha256=null;expect(evaluateTravelCaseRecipe('travel.ticket_options',i)).toMatchObject({allowed:true});});
 it('keeps daily fare assessment independent of a changed monthly pass operand',()=>{const i=fixture(),before=travelCaseConsumed(i,evaluateTravelCaseRecipe('travel.fare_basis',i).consumed_paths);i.monthly_pass_cost!.printed_value='210.00';expect(evaluateTravelCaseRecipe('travel.fare_basis',i)).toMatchObject({allowed:true});expect(travelCaseConsumed(i,evaluateTravelCaseRecipe('travel.fare_basis',i).consumed_paths)).toEqual(before);expect(evaluateTravelCaseRecipe('travel.ticket_options',i)).toMatchObject({allowed:false,reason:'identified_monthly_pass_cell_required'});});
 it('does not infer better-arrangement absence or one-direction legal interpretation',()=>{const i=fixture();i.product_facts!.other_travel_terms_known={state:'observed',value:false,source};expect(evaluateTravelCaseRecipe('travel.no_better_arrangement',i)).toMatchObject({allowed:false,reason:'arrangement_source_scope_missing'});expect(evaluateTravelCaseRecipe('travel.one_direction_treatment',i)).toMatchObject({allowed:false,reason:'one_direction_interpretation_required'});});
 it('rejects foreign version/hash/read receipts and source kinds',()=>{for(const field of ['version_id','file_sha256','reading_receipt_sha256'] as const){const i=fixture();i.fare_source_context!.association.source={...source,[field]:field==='version_id'?'foreign-version':'b'.repeat(64)};expect(()=>evaluateTravelCaseRecipe('travel.fare_basis',i,review(i))).toThrow();}const i=fixture();i.product_facts!.employment_relationship.state='declared';expect(()=>evaluateTravelCaseRecipe('travel.general_coverage',i)).toThrow('TRAVEL_PRODUCT_FACT_BASIS');});
 it('replays a pinned method and preserves independent raw decisions after a supported correction',()=>{const i=bind(fixture()),independent={decision_id:'travel.no_better_arrangement',state:'accepted' as const,basis:'ai_source_assessment' as const,explanation:'Synthetic separately reviewed arrangement',sources:[travelLegalSource(1,'Synthetic arrangement')],valid_until:null};i.applicability.push(independent);expect(replayTravelProductFacts(i,i,review(i))).toEqual(i);const next=structuredClone(i);next.commute_days!.printed_value='19';const out=replayTravelProductFacts(next,i,review(i));expect(out.applicability[0].state).toBe('stale');expect(out.applicability[1]).toEqual(independent);expect(i.applicability[0].state).toBe('accepted');});
 it('rejects a forged method, duplicate binding or expiry, but keeps source extraction time independent',()=>{const i=bind(fixture());expect(()=>replayTravelProductFacts(i,i,review(i))).not.toThrow();for(const kind of ['hash','source','expired','duplicate']){const j=structuredClone(i),b=j.case_recipe_bindings![0];if(kind==='hash')b.method.recipe_sha256=sha;if(kind==='source')b.method.source_receipts[0].artifact_sha256=sha;if(kind==='expired')b.method.expires_at=b.evaluated_at;if(kind==='duplicate')j.case_recipe_bindings!.push(b);else{const {binding_sha256,...body}=b;void binding_sha256;b.binding_sha256=canonicalSha256(body);}expect(()=>replayTravelProductFacts(j,j,review(j))).toThrow();}});
});
