import {z} from 'zod';
import {resolveCaseAccessDb,resolveReportOperationsDb,type CaseAccessDb} from '../case-access/db';
import {elapsedServiceMs} from '../reports/business-clock';
export const supportRequestSchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('support_open'),id:z.uuid(),message:z.string().trim().min(4).max(2000)}).strict(),
 z.object({action:z.literal('support_reply'),id:z.uuid(),threadId:z.uuid(),message:z.string().trim().min(4).max(2000)}).strict(),
]);
export const supportOwnerReplySchema=z.object({id:z.uuid(),threadId:z.uuid(),revision:z.number().int().positive(),message:z.string().trim().min(4).max(2000),state:z.enum(['waiting_customer','resolved']),priority:z.enum(['normal','urgent'])}).strict();
export type SupportThread={id:string;origin:'case'|'finding';report_id:string|null;finding_id:string|null;state:'open'|'waiting_customer'|'resolved';revision:number;created_at:string;messages:{id:string;author_kind:'customer'|'owner';message:string;created_at:string}[]};
export type SupportQueueItem=SupportThread&{public_id:string;priority:'normal'|'urgent';target_exceeded:boolean|null};
export function requireSupportOwner(actor:{actor_id:string;verified_server_side:boolean},configured=process.env.TIVDOC_SUPPORT_OWNER_ACTOR_ID){if(!configured||!actor.verified_server_side||actor.actor_id!==configured)throw Object.assign(new Error('OPS_FORBIDDEN'),{code:'OPS_FORBIDDEN'});}
async function store(db:CaseAccessDb|undefined,operations=false){const result=db??await(operations?resolveReportOperationsDb():resolveCaseAccessDb());if(!result)throw new Error('SUPPORT_STORE_UNAVAILABLE');return result;}
export async function customerSupport(caseId:string,identityId:string,db?:CaseAccessDb){const s=await store(db);const value=(await s.rpc<{value:SupportThread[]}>('case_request_support_list',{target_case:caseId,target_identity:identityId}))[0]?.value;if(!Array.isArray(value))throw new Error('SUPPORT_STORE_UNAVAILABLE');return value;}
export async function submitSupport(caseId:string,identityId:string,raw:unknown,db?:CaseAccessDb){const body=supportRequestSchema.parse(raw),s=await store(db);const rows=await s.rpc<{value:string}>(body.action==='support_open'?'case_request_support_open':'case_request_support_reply',{target_id:body.id,target_case:caseId,target_identity:identityId,target_message:body.message,...(body.action==='support_reply'?{target_thread:body.threadId}:{})});if(rows[0]?.value!==body.id)throw new Error('SUPPORT_SAVE_UNCONFIRMED');return body.id;}
export async function supportQueue(db?:CaseAccessDb,now=Date.now()){const s=await store(db,true);const rows=(await s.rpc<{value:Omit<SupportQueueItem,'target_exceeded'>[]}>('case_request_support_queue',{}))[0]?.value;if(!Array.isArray(rows))throw new Error('SUPPORT_STORE_UNAVAILABLE');return rows.map(t=>{let target:boolean|null=false;try{target=t.state==='open'&&elapsedServiceMs(Date.parse(t.messages.slice(t.messages.findLastIndex(m=>m.author_kind==='owner')+1).find(m=>m.author_kind==='customer')?.created_at??t.created_at),now,[],'human')>=16*3600000;}catch{target=null;}return {...t,target_exceeded:target};});}
export async function ownerSupportReply(actor:string,raw:unknown,db?:CaseAccessDb){const body=supportOwnerReplySchema.parse(raw),s=await store(db,true);const rows=await s.rpc<{value:string}>('case_request_support_owner_reply',{target_id:body.id,target_thread:body.threadId,target_revision:body.revision,target_actor:actor,target_message:body.message,target_state:body.state,target_priority:body.priority});if(rows[0]?.value!==body.id)throw new Error('SUPPORT_SAVE_UNCONFIRMED');return body.id;}
