import type {CaseAccessDb} from '../case-access/db';
import {describe,it,expect,vi} from 'vitest';
import {supportQueue,requireSupportOwner,supportRequestSchema,supportOwnerReplySchema,submitSupport} from './support';
vi.mock('server-only',()=>({}));
describe('owner support authority and customer submission',()=>{
 it('times the first unanswered message and keeps an unknown calendar visible',async()=>{const thread={id:'synthetic',state:'open',created_at:'2026-09-07T06:00:00Z',messages:[{author_kind:'customer',created_at:'2026-09-07T06:00:00Z'},{author_kind:'customer',created_at:'2026-09-09T13:00:00Z'}]};const db={provider:'fake' as const,rpc:async<T>()=>[{value:[thread]}] as T[]};expect((await supportQueue(db,Date.parse('2026-09-09T14:00:00Z')))[0].target_exceeded).toBe(true);expect((await supportQueue(db,Date.parse('2027-01-01T14:00:00Z')))[0].target_exceeded).toBeNull();});

 it('does not grant support access to an arbitrary verified reviewer or an unverified owner',()=>{expect(()=>requireSupportOwner({actor_id:'reviewer',verified_server_side:true},'owner')).toThrow('OPS_FORBIDDEN');expect(()=>requireSupportOwner({actor_id:'owner',verified_server_side:false},'owner')).toThrow('OPS_FORBIDDEN');expect(()=>requireSupportOwner({actor_id:'owner',verified_server_side:true},'')).toThrow('OPS_FORBIDDEN');expect(()=>requireSupportOwner({actor_id:'owner',verified_server_side:true},'owner')).not.toThrow();});
 it('keeps case and actor authority out of customer input',()=>{expect(supportRequestSchema.safeParse({action:'support_open',id:crypto.randomUUID(),message:'hello',caseId:crypto.randomUUID()}).success).toBe(false);expect(supportOwnerReplySchema.safeParse({id:crypto.randomUUID(),threadId:crypto.randomUUID(),revision:1,message:'hello',state:'resolved',priority:'urgent',actor:'someone'}).success).toBe(false);});
 it('does not confirm a message when the store returned no save receipt',async()=>{await expect(submitSupport('case','identity',{action:'support_open',id:crypto.randomUUID(),message:'Hello support'},{provider:'fake',rpc:async()=>[]})).rejects.toThrow('SUPPORT_SAVE_UNCONFIRMED');});
 it('uses the resolved identity and keeps the same request ID on a retry',async()=>{const request={action:'support_open',id:crypto.randomUUID(),message:'  Hello support  '},rpc=vi.fn(async<T>()=>[{value:request.id}] as T[]);await submitSupport('saved-case','saved-owner',request,{provider:'fake',rpc:rpc as unknown as CaseAccessDb['rpc']});await submitSupport('saved-case','saved-owner',request,{provider:'fake',rpc:rpc as unknown as CaseAccessDb['rpc']});expect(rpc.mock.calls[0]).toEqual(rpc.mock.calls[1]);expect(rpc).toHaveBeenCalledWith('case_request_support_open',{target_id:request.id,target_case:'saved-case',target_identity:'saved-owner',target_message:'Hello support'});});
});
