import {describe,it,expect} from 'vitest';
import {canonicalSha256} from '../../rule-runtime/canonical.ts';
import {documentReviewInputSchema} from '../../document-review/contracts.ts';
import {AI_RELEASE_DECISION_RECIPES} from '../../ai-release-decisions/catalog.ts';
import {convalescenceEntitlementInputSchema,type ConvalescenceEntitlementInput} from './contracts.ts';
import {evaluateConvalescenceCaseRecipe,convalescenceCaseConsumed,convalescenceCaseSegmentReadiness,convalescenceSourceChainReadiness,validateConvalescenceCaseMethod} from './product-decisions.ts';
import {CONVALESCENCE_PINNED_LEGAL_DOCUMENTS,CONVALESCENCE_SOURCE_REVIEW_SHA256} from './source-policy.ts';

const sha='a'.repeat(64),source={document_id:'synthetic-employment-payment',version_id:'synthetic-v1',file_sha256:sha,page:1,locator:'Synthetic explicit benefit-year, coverage, due date and allocated inventory',label:'Synthetic source only',reading:'identified_document_reading' as const,reading_receipt_sha256:'b'.repeat(64)};
const fact=(value:unknown)=>({state:'observed',value,source});
function fixture():ConvalescenceEntitlementInput{const coverage={from:'2025-06-01',to:'2026-05-31'};return convalescenceEntitlementInputSchema.parse({schema_version:'convalescence-entitlement-input-v1',catalog_version:'1.0.0',case_id:'synthetic-case',run_id:'synthetic-run',check_prefix:'synthetic.cv',period:{from:'2026-06-01',to:'2026-06-30'},evaluated_at:'2026-09-12T00:00:00Z',source_manifest:[{document_id:source.document_id,version_id:source.version_id,file_sha256:sha,page_count:2,kind:'case_document',case_id:'synthetic-case'}],population:fact('adult_private_general_21_59'),employment_start:fact('2025-06-01'),qualifying_service:fact('continuous_no_excluded_absence'),payment_coverage:fact(coverage),benefit_year:fact(2026),due_date:fact('2026-06-30'),segments:[{id:'synthetic.half',period:fact(coverage),fte:fact('0.5')}],recorded:{id:'synthetic.recorded',observation_id:'synthetic.recorded',state:'observed',printed_value:'1000.00',representation:'money_ils',quantity_unit:null,precision:'printed_precision',source},recorded_coverage:fact(coverage),recorded_inventory:fact('complete_allocated'),applicability:[]});}
function review(i:ConvalescenceEntitlementInput){return documentReviewInputSchema.parse({schema_version:'document-review-product-v1',case_id:i.case_id,period:i.period,purchased_scope:{order_id:'synthetic-order',receipt_sha256:sha,origin:'saved_order',topics:['convalescence']},documents:[{case_id:i.case_id,document_id:source.document_id,version_id:source.version_id,file_sha256:sha,page_count:2,kind:'other',label:'Synthetic benefit source',period:i.period,reading_origin:'identified_document_reading',reading_sha256:source.reading_receipt_sha256}],checks:[],completion_input:{},answer_history:[],answer_bindings:[],coverage_gaps:[]});}
describe('convalescence fact-backed case predicates, without an alternate executor',()=>{
 it.each(['cv.benefit_year','cv.qualifying_service','cv.due_date','cv.allocation'])('reports source-bound readiness for %s without writing applicability or facts',id=>{const i=fixture(),before=canonicalSha256(i),r=evaluateConvalescenceCaseRecipe(id,i,review(i));expect(r.allowed).toBe(true);expect(r.consumed_sha256).toBe(canonicalSha256(convalescenceCaseConsumed(i,r.consumed_paths)));expect(r.source_sha256s.length).toBeGreaterThan(0);expect(canonicalSha256(i)).toBe(before);expect(i.applicability).toEqual([]);});
 it.each(['missing','unknown','conflict','stale','expired','unreadable'] as const)('keeps explicit %s benefit year blocked even though the payslip is in 2026',state=>{const i=fixture();i.benefit_year={state,value:null,source:null};expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i)).toMatchObject({allowed:false,reason:'benefit_year:'+state});});
 it('accepts explicitly named benefit year with cross-calendar-year coverage rather than inventing July–June',()=>{const i=fixture();expect(i.payment_coverage.value).toEqual({from:'2025-06-01',to:'2026-05-31'});expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i).allowed).toBe(true);i.benefit_year.value=2025;expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i)).toMatchObject({allowed:false,reason:'benefit_year:unsupported_or_prior_year'});});
 it('does not use the August source at a pre-publication knowledge date',()=>{const i=fixture();i.evaluated_at='2026-08-17T23:59:59Z';expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i)).toMatchObject({allowed:false,reason:'source_not_yet_published_at_knowledge_date'});});
 it('requires an actual due-date answer instead of choosing a date within the summer',()=>{const i=fixture();i.due_date={state:'unknown',value:null,source:null};expect(evaluateConvalescenceCaseRecipe('cv.due_date',i)).toMatchObject({allowed:false,reason:'due_date:unknown'});i.due_date={...fixture().due_date,value:'2026-07-01'};expect(evaluateConvalescenceCaseRecipe('cv.due_date',i)).toMatchObject({allowed:false,reason:'due_date:outside_selected_payroll_month'});});
 it('keeps completion of the first year and excluded absences separate from FTE',()=>{const i=fixture();i.employment_start.value='2026-01-01';i.payment_coverage.value={from:'2026-01-01',to:'2026-05-31'};expect(evaluateConvalescenceCaseRecipe('cv.qualifying_service',i)).toMatchObject({allowed:false,reason:'first_year:not_completed_by_due_date'});i.employment_start.value='2025-01-01';i.qualifying_service.value='excluded_absence_or_break';expect(evaluateConvalescenceCaseRecipe('cv.qualifying_service',i)).toMatchObject({allowed:false,reason:'qualifying_service:excluded_absence_or_break'});});
 it('does not invent FTE, treat zero as a leave adjustment, or fill a coverage gap',()=>{const i=fixture();i.segments[0].fte={state:'missing',value:null,source:null};expect(convalescenceCaseSegmentReadiness(i)).toMatchObject({allowed:false,reason:'segments.0.fte:missing'});i.segments[0].fte={...fixture().segments[0].fte,value:'0'};expect(convalescenceCaseSegmentReadiness(i)).toMatchObject({allowed:false,reason:'segments.0.fte:zero_requires_absence_review'});i.segments[0].fte.value='0.5';i.segments[0].period.value!.to='2026-05-30';expect(convalescenceCaseSegmentReadiness(i)).toMatchObject({allowed:false,reason:'segments:incomplete_coverage'});});
 it('requires disjoint complete periods and preserves duplicated segments as a conflict',()=>{const i=fixture();i.segments.push(structuredClone(i.segments[0]));expect(convalescenceCaseSegmentReadiness(i)).toMatchObject({allowed:false,reason:'segments:duplicate'});i.segments[1].id='synthetic.second';expect(convalescenceCaseSegmentReadiness(i)).toMatchObject({allowed:false,reason:'segments:overlap_gap_or_outside_coverage'});});
 it('does not silently choose an anniversary for a leap-day hire',()=>{const i=fixture();i.employment_start.value='2024-02-29';expect(evaluateConvalescenceCaseRecipe('cv.qualifying_service',i)).toMatchObject({allowed:false,reason:'employment_start:leap_anniversary_method_required'});});
 it('accepts an explicit factual declaration as a declaration without promoting it to a document reading',()=>{const i=fixture(),answer={...source,document_id:'synthetic-answer',version_id:'synthetic-answer:1',reading:'customer_declaration' as const,reading_receipt_sha256:sha};i.benefit_year={state:'declared',value:2026,source:answer};i.source_manifest.push({document_id:answer.document_id,version_id:answer.version_id,file_sha256:sha,page_count:1,kind:'customer_answer',case_id:i.case_id});expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i).allowed).toBe(true);expect(i.benefit_year.state).toBe('declared');i.benefit_year.state='observed';expect(evaluateConvalescenceCaseRecipe('cv.benefit_year',i)).toMatchObject({allowed:false,reason:'benefit_year:observed_basis_mismatch'});});
 it('limits missing recorded allocation to comparison and keeps expected predicates unchanged',()=>{const i=fixture(),before=evaluateConvalescenceCaseRecipe('cv.qualifying_service',i);i.recorded=null;expect(evaluateConvalescenceCaseRecipe('cv.allocation',i)).toMatchObject({allowed:false,reason:'recorded:identified_amount_required',dependent_check_ids:['synthetic.cv.comparison']});expect(evaluateConvalescenceCaseRecipe('cv.qualifying_service',i)).toEqual(before);});
 it('preserves a recorded zero and rejects a partial or differently scoped payment inventory',()=>{const i=fixture();i.recorded!.printed_value='0.00';expect(evaluateConvalescenceCaseRecipe('cv.allocation',i).allowed).toBe(true);i.recorded_inventory.value='partial';expect(evaluateConvalescenceCaseRecipe('cv.allocation',i)).toMatchObject({allowed:false,reason:'recorded_inventory:complete_allocation_required'});i.recorded_inventory.value='complete_allocated';i.recorded_coverage.value={from:'2026-01-01',to:'2026-05-31'};expect(evaluateConvalescenceCaseRecipe('cv.allocation',i)).toMatchObject({allowed:false,reason:'recorded_coverage:period_mismatch'});});
 it('requires identified allocation evidence, not a customer estimate of complete payment',()=>{const i=fixture();i.recorded_inventory.source={...source,page:2};expect(evaluateConvalescenceCaseRecipe('cv.allocation',i)).toMatchObject({allowed:false,reason:'recorded_allocation:source_group_mismatch'});i.recorded_inventory.source=source;i.recorded!.state='declared';expect(evaluateConvalescenceCaseRecipe('cv.allocation',i)).toMatchObject({allowed:false,reason:'recorded:identified_amount_required'});});
 it('rejects foreign source/file/reading pins and case-period context rather than lowering trust',()=>{for(const field of ['version_id','file_sha256','reading_receipt_sha256'] as const){const i=fixture();i.benefit_year.source={...source,[field]:field==='version_id'?'foreign':'c'.repeat(64)};expect(()=>evaluateConvalescenceCaseRecipe('cv.benefit_year',i,review(i))).toThrow();}const i=fixture(),r=review(i);r.case_id='foreign';expect(()=>evaluateConvalescenceCaseRecipe('cv.due_date',i,r)).toThrow('CV_CASE_SCOPE');});
 it('separates pinned source-chain completeness from population and better-arrangement admission',()=>{const i=fixture(),recipe=AI_RELEASE_DECISION_RECIPES.find(r=>r.recipe_id==='ai-method.cv.proration')!;const method={recipe_id:recipe.recipe_id,recipe_version:recipe.recipe_version,recipe_sha256:recipe.recipe_sha256,source_policy_sha256:CONVALESCENCE_SOURCE_REVIEW_SHA256,interpretation_receipt_sha256:sha,source_receipts:CONVALESCENCE_PINNED_LEGAL_DOCUMENTS.map(s=>({receipt_sha256:sha,source_version_id:s.version_id,artifact_sha256:s.file_sha256})),issued_at:'2026-09-11T00:00:00Z',expires_at:'2026-09-13T00:00:00Z'};
  expect(convalescenceSourceChainReadiness(i,method,i.evaluated_at)).toMatchObject({legal_chain_ready:true,arrangement_ready:false,legacy_combined_decision_allowed:false,publication_authority:false});i.population.value='public_or_pegged';expect(convalescenceSourceChainReadiness(i,method,i.evaluated_at)).toMatchObject({legal_chain_ready:true,population:'public_or_pegged',legacy_combined_decision_allowed:false});method.source_receipts.pop();expect(convalescenceSourceChainReadiness(i,method,i.evaluated_at).legal_chain_ready).toBe(false);expect(evaluateConvalescenceCaseRecipe('cv.source_chain',i)).toMatchObject({allowed:false,reason:'source_chain_and_arrangement_must_be_assessed_separately'});
 });
 it('requires an actual compiled case method before using readiness as an admission input',()=>{const i=fixture();const fake={recipe_id:'ai-case.cv.benefit_year',recipe_version:'1' as const,recipe_sha256:sha,source_policy_sha256:CONVALESCENCE_SOURCE_REVIEW_SHA256,interpretation_receipt_sha256:sha,source_receipts:[],issued_at:'2026-09-11T00:00:00Z',expires_at:'2026-09-13T00:00:00Z'};expect(()=>validateConvalescenceCaseMethod(fake,i.evaluated_at,i)).toThrow('CV_CASE_METHOD_BINDING');});
});
