import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';import {createClient} from '@supabase/supabase-js';import {PDFDocument} from 'pdf-lib';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';import {postgresCaseAccessDb,type CaseAccessDb} from '../../src/server/product/case-access/db.ts';import {collectOrphans} from '../../src/server/product/privacy/storage-gc.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString()});}const db=client('TIVDOC_DEV_DATABASE_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL');await Promise.all([db.connect(),worker.connect()]);
const keyResult=spawnSync('npx.cmd',['--yes','supabase','projects','api-keys','--project-ref',TIVDOC_DEV_PROJECT_REF,'--output','json'],{encoding:'utf8',shell:true,windowsHide:true,timeout:30000});assert.equal(keyResult.status,0);const key=JSON.parse(keyResult.stdout).find((k:{name:string})=>k.name==='service_role')?.api_key;assert.ok(key);const storage=createClient(`https://${TIVDOC_DEV_PROJECT_REF}.supabase.co`,key,{auth:{persistSession:false}}).storage.from('salary-documents');
const caseId=randomUUID(),doc=randomUUID(),version=randomUUID(),orphan=`cases/${caseId}/versions/${randomUUID()}.pdf`,path=`cases/${caseId}/versions/${version}.pdf`;const pdf=await PDFDocument.create();pdf.addPage();const bytes=Buffer.from(await pdf.save()),sha=createHash('sha256').update(bytes).digest('hex'),checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{
 await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month,contact_verified_at,is_qa) values($1,'Synthetic GC','synthetic@example.invalid','0500000000','documents_uploaded','not_started','2026-06-01',now(),true)",[caseId]);
 for(const object of [path,orphan])assert.equal((await storage.upload(object,bytes,{contentType:'application/pdf',upsert:false})).error,null);
 await db.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size,content_sha256) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',$5,$6)",[doc,caseId,version,path,bytes.length,sha]);
 const store=postgresCaseAccessDb(worker),objects=[path,orphan].map(path=>({path,createdAt:'2026-01-01T00:00:00Z'}));let removes=0;const port={remove:async(path:string)=>{const response=await storage.remove([path]);assert.equal(response.error,null);removes++;}};
 const mark=await collectOrphans({db:store,storage:port,objects,execute:false});assert.equal(mark.retained,1);assert.equal(mark.marked,1);assert.ok((await storage.download(orphan)).data);pass('mark-only run preserves both actual Storage objects and retains the linked document');
 await db.query("update private.storage_gc_candidates set eligible_at=now()-interval '1 second' where path=$1",[orphan]);
 const failed=await collectOrphans({db:store,storage:{remove:async()=>{throw new Error('synthetic disconnect');}},objects,execute:true});assert.equal(failed.failed,1);assert.ok((await storage.download(orphan)).data);pass('disconnect before remove leaves actual bytes intact');
 let failOnce=true;const crashStore:CaseAccessDb={provider:'postgres',rpc:async<T>(fn,args)=>{if(fn==='case_documents_gc_finish'&&failOnce){failOnce=false;throw new Error('synthetic process crash');}return store.rpc<T>(fn,args);}};
 assert.equal((await collectOrphans({db:crashStore,storage:port,objects,execute:true})).failed,1);assert.equal(removes,1);const listing=await storage.list(`cases/${caseId}/versions`,{search:orphan.split('/').at(-1)!});assert.equal(listing.error,null);assert.equal(listing.data?.length,0);assert.equal((await db.query('select state from private.storage_gc_candidates where path=$1',[orphan])).rows[0].state,'deleting');
 assert.equal((await collectOrphans({db:store,storage:port,objects,execute:true})).deleted,1);pass('crash after actual removal resumes the same fenced deletion and acknowledges it once');
 const live=await storage.download(path);assert.ok(live.data);assert.equal(createHash('sha256').update(Buffer.from(await live.data.arrayBuffer())).digest('hex'),sha);assert.equal((await db.query('select storage_path from public.documents where id=$1',[doc])).rows[0].storage_path,path);pass('live document remains linked and byte-identical after deletion retries');
 writeFileSync('docs/release-evidence/P10-gc-storage.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',storageProject:'allowlisted DEV',fixtures:'synthetic QA; controlled clock/grace advancement',actualStorageRemove:true,production:'untouched'},null,2)+'\n');
}finally{await storage.remove([path,orphan]);await db.query('delete from private.storage_gc_candidates where case_id=$1',[caseId]);await db.query("delete from public.cases where id=$1 and first_name='Synthetic GC'",[caseId]);await Promise.all([db.end(),worker.end()]);}
