import '../production-refusal.mjs';
import {legacyFullOfferFixture} from '../../src/server/product/orders/fixtures/legacy-offer.ts';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';import {offerSnapshot} from '../../src/server/product/orders/contracts.ts';import {S04_HIGH_CERTAINTY} from '../../src/server/product/reports/case-report-projection.fixtures.ts';import {canonicalSha256} from '../../src/engine/rule-runtime/canonical.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString(),connectionTimeoutMillis:15000});}
const db=client('TIVDOC_DEV_DATABASE_URL'),ops=client('TIVDOC_OPERATIONS_POSTGRES_URL'),web=client('TIVDOC_WEB_POSTGRES_URL');await Promise.all([db.connect(),ops.connect(),web.connect()]);const ids=[randomUUID(),randomUUID()],reports:string[]=[],checks:string[]=[];let identity:string|undefined;const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};const since=new Date(Date.now()-3600000).toISOString();const metrics=async()=> (await ops.query('select public.case_funnel_metrics($1,clock_timestamp()) value',[since])).rows[0].value;
async function cleanupMetrics(caseIds:string[]){await db.query('begin');try{
 const identities=(await db.query('select identity_id from public.case_identity_cases where case_id=any($1::uuid[])',[caseIds])).rows.map(r=>r.identity_id);
 for(const table of ['case_report_projections','case_report_qa','case_report_qa_log'])await db.query(`create policy metrics_cleanup on public.${table} for all to tivdoc_dev_migrator using(case_id=any(array[${caseIds.map(id=>"'"+id+"'::uuid").join(',')}])) with check(false)`);
 // Owned synthetic DEV rows only, with exclusive table lock and transactional restoration.
 await db.query('alter table public.case_report_qa_log disable trigger case_report_qa_log_no_update');await db.query("delete from public.cases where id=any($1::uuid[]) and first_name='Synthetic metrics' and email='synthetic@example.invalid'",[caseIds]);await db.query('alter table public.case_report_qa_log enable trigger case_report_qa_log_no_update');
 for(const table of ['case_report_projections','case_report_qa','case_report_qa_log'])await db.query(`drop policy metrics_cleanup on public.${table}`);
 await db.query('delete from public.case_identities i where id=any($1::uuid[]) and not exists(select 1 from public.case_identity_cases c where c.identity_id=i.id)',[identities]);await db.query('commit');
}catch(e){await db.query('rollback');throw e;}}

try{
 if(!(await db.query("select to_regprocedure('public.case_funnel_metrics(timestamptz,timestamptz)') value")).rows[0].value)await db.query(readFileSync('supabase/migrations/20260907140000_product_metrics.sql','utf8'));
 else {const sql=readFileSync('supabase/migrations/20260907140000_product_metrics.sql','utf8');await db.query(sql.slice(sql.indexOf('create or replace function public.case_funnel_metrics'),sql.indexOf('revoke all on function public.case_funnel_metrics')));}

 const stale=(await db.query("select id from public.cases where first_name='Synthetic metrics' and email='synthetic@example.invalid'")).rows.map(r=>r.id);if(stale.length)await cleanupMetrics(stale);
 const before=await metrics();await assert.rejects(web.query('select public.case_funnel_metrics($1,now())',[since]),/permission denied/);pass('customer web role cannot read operational metrics');
 for(const [index,id] of ids.entries()){
  await db.query('begin');
  await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month,contact_verified_at,is_qa) values($1,'Synthetic metrics','synthetic@example.invalid','0500000000','under_review','verified','2026-06-01',now(),$2)",[id,index===1]);
  await db.query("insert into public.payments(case_id,provider,amount,status,verified_at,idempotency_key) values($1,'synthetic',9.99,'verified',now(),$2)",[id,randomUUID()]);
  const reportId=randomUUID(),docId=randomUUID(),versionId=randomUUID(),evidenceId=randomUUID(),orderId=randomUUID();reports.push(reportId);
  await db.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size,content_sha256) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',100,$5)",[docId,id,versionId,`cases/${id}/versions/${versionId}.pdf`,'b'.repeat(64)]);
  const offer=offerSnapshot('initial');await db.query("insert into private.product_orders(id,case_id,kind,period_from,period_to,amount_minor,currency,offer,offer_sha256,topics,terms_version,state,verified_at) values($1,$2,'initial','2026-06-01','2026-06-01',999,'ILS',$3,$4,array['minimum_wage'],$5,'paid',now())",[orderId,id,offer,offer.sha256,offer.terms_version]);await db.query("insert into private.order_entitlements(order_id,state) values($1,'active')",[orderId]);
  const input=(await db.query('select * from private.case_input_heads where case_id=$1',[id])).rows[0],publicId=(await db.query('select public_id from public.cases where id=$1',[id])).rows[0].public_id,projection={...S04_HIGH_CERTAINTY,case_public_id:publicId};
  const document={schema_version:'tivdoc-report-document-v2',id:reportId,case_id:id,order_id:orderId,revision:1,input_sha256:input.input_sha256,projection_sha256:canonicalSha256(projection),purchased_period:{from:'2026-06',to:'2026-06'},projection,evidence:[{id:evidenceId,document_id:docId,version_id:versionId,sha256:'b'.repeat(64),page:1,field:'gross',fact_version:'synthetic-v1'}],findings:[{id:randomUUID(),topic:'minimum_wage',evidence_ids:[evidenceId],rule_versions:['synthetic-rule'],parameter_versions:['synthetic-param']}],publication:{state:'draft',approved_input_sha256:null,approval_actor_kind:null,published_at:null},correction_policy:'append_new_revision_preserve_published'};
  await db.query('create policy metrics_probe on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');await db.query("insert into public.case_report_projections(id,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,generated_at,input_revision,report_document) values($1,$2,$3,'initial','2026-06-01',$4,$5,$6,now(),$7,$8)",[reportId,id,projection.schema_version,projection,canonicalSha256(projection),projection.legal_basis,input.revision,document]);await db.query('drop policy metrics_probe on public.case_report_projections');await db.query('commit');
  await ops.query("select * from public.case_report_qa_enqueue($1,$2,'initial','automatic',array[]::text[],'published','system:publication_gate')",[id,reportId]);
 }
 const after=await metrics();assert.equal(after.sample.cases,before.sample.cases+1);assert.equal(after.sample.qa_cases_excluded,before.sample.qa_cases_excluded+1);assert.equal(after.counts.reports,before.counts.reports+1);assert.equal(after.counts.cases_with_finding,before.counts.cases_with_finding+1);pass('published findings and verified payments come from actual rows while QA is excluded');
 identity=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[createHash('sha256').update(ids[0]).digest('hex')])).rows[0].id;await db.query('select public.case_access_identity_link($1,$2)',[identity,ids[0]]);
 await web.query('select public.case_report_open($1,$2,$3)',[ids[0],identity,reports[0]]);await web.query('select public.case_report_open($1,$2,$3)',[ids[0],identity,reports[0]]);assert.equal((await metrics()).sample.opened_cases,before.sample.opened_cases+1);pass('visible report opening is scoped and idempotent');await assert.rejects(web.query('select public.case_report_open($1,$2,$3)',[ids[1],identity,reports[1]]),/REPORT_FORBIDDEN/);pass('another case report cannot be linked as an opening');
 const full=legacyFullOfferFixture();await db.query("insert into private.product_orders(id,case_id,kind,period_from,period_to,amount_minor,currency,offer,offer_sha256,topics,terms_version,state,verified_at) values($1,$2,'full','2026-06-01','2026-06-01',14900,'ILS',$3,$4,array['minimum_wage'],$5,'paid',now())",[randomUUID(),ids[0],full,full.sha256,full.terms_version]);assert.equal((await metrics()).counts.full_reports_purchased,before.counts.full_reports_purchased+1);pass('full purchase count is read from a paid scoped order instead of default zero');
 await assert.rejects(ops.query("select public.case_funnel_metrics(now(),now()-interval '1 day')"),/METRICS_WINDOW_INVALID/);pass('invalid reporting windows are refused');
 writeFileSync('docs/release-evidence/P12-metrics-db.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',fixtures:'synthetic: one explicitly non-QA classification control and one QA control; both removed',providerVerified:false,browserOpeningProven:false,production:'untouched'},null,2)+'\n');
 }finally{await db.query('rollback');try{await cleanupMetrics(ids);}finally{await Promise.all([db.end(),ops.end(),web.end()]);}}
