import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);
function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString(),connectionTimeoutMillis:15000});}
const db=client('TIVDOC_DEV_DATABASE_URL'),web=client('TIVDOC_WEB_POSTGRES_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL'),peer=client('TIVDOC_WORKER_POSTGRES_URL');await Promise.all([db.connect(),web.connect(),worker.connect(),peer.connect()]);
let fixtureIdentity:string|undefined;const caseId=randomUUID(),w1=randomUUID(),w2=randomUUID(),provider=randomUUID();const delivery=createHash('sha256').update(caseId).digest('hex');const recipient=createHash('sha256').update('synthetic:'+caseId).digest('hex');const eventId='test_'+caseId;const checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{
 for(const [exists,file] of [["to_regprocedure('public.case_notification_outbox_claim(uuid)')",'20260907093000_notification_outbox.sql']] as const){if(!(await db.query(`select ${exists} value`)).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/'+file,'utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}}
 if(!(await db.query("select to_regprocedure('public.case_notification_outbox_enqueue(text,uuid,uuid,text,text,jsonb,timestamptz,text)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907095000_notification_product_bridge.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select pg_get_functiondef('public.case_access_session_resolve(text,integer,integer)'::regprocedure) value")).rows[0].value.includes('for update'))await db.query(readFileSync('supabase/migrations/20260907090000_session_revocation_fence.sql','utf8'));
 if(!(await db.query("select to_regprocedure('public.case_notification_request_reminders(integer)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907100000_notification_reminders.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 await db.query(readFileSync('supabase/migrations/20260907100500_webhook_worker_grant.sql','utf8'));
 if(!(await db.query("select to_regprocedure('public.case_notification_reminder_enqueue(uuid,text,text,uuid,uuid,text,jsonb,timestamptz)') value")).rows[0].value)await db.query(readFileSync('supabase/migrations/20260907101000_notification_race_guards.sql','utf8'));
 await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month) values($1,'Synthetic notification','synthetic@example.invalid','0500000000','started','not_started','2026-08-01')",[caseId]);
 const args=[delivery,caseId,null,recipient,'access_code',{version:1,iv:'synthetic',tag:'synthetic',ciphertext:'encrypted-contract-fixture'},new Date(Date.now()+300000)];
 await web.query('select public.case_notification_outbox_enqueue($1,$2,$3,$4,$5,$6,$7)',args);await web.query('select public.case_notification_outbox_enqueue($1,$2,$3,$4,$5,$6,$7)',args);assert.equal((await db.query('select count(*)::int n from private.case_notification_outbox where delivery_id=$1',[delivery])).rows[0].n,1);pass('enqueue retry persists one encrypted intention');
 await web.query("select public.case_notification_record($1,null,'email','access_code','queued','resend_outbox',$2,null)",[caseId,delivery]);
 const claims=await Promise.all([worker.query('select * from public.case_notification_outbox_claim($1)',[w1]),peer.query('select * from public.case_notification_outbox_claim($1)',[w2])]);assert.equal(claims[0].rowCount!+claims[1].rowCount!,1);const index=claims[0].rowCount?0:1;const row=claims[index].rows[0],owner=index===0?w1:w2;pass('concurrent actual workers claim the intention once');
 await assert.rejects(worker.query('select public.case_notification_outbox_finish($1,$2,$3,$4,null)',[delivery,owner,row.fencing_token+1,provider]),/NOTIFICATION_LEASE_LOST/);pass('stale fencing token cannot acknowledge another attempt');
 const at=new Date();await db.query("select public.case_notification_webhook_record($1,$2,'email.delivered',$3)",[eventId,provider,at]);await db.query("select public.case_notification_webhook_record($1,$2,'email.delivered',$3)",[eventId,provider,at]);
 await worker.query('select public.case_notification_outbox_finish($1,$2,$3,$4,null)',[delivery,owner,row.fencing_token,provider]);const delivered=(await db.query('select state,encrypted_payload from private.case_notification_outbox where delivery_id=$1',[delivery])).rows[0];assert.equal(delivered.state,'delivered');assert.equal(delivered.encrypted_payload,null);pass('early duplicated delivery webhook is reconciled after API acceptance; secret message is removed');
 assert.equal((await db.query('select state from public.case_notifications where payload_sha256=$1',[delivery])).rows[0].state,'delivered');
 await web.query("select public.case_notification_record($1,null,'email','access_code','queued','resend_outbox',$2,null)",[caseId,delivery]);
 assert.equal((await db.query('select state from public.case_notifications where payload_sha256=$1',[delivery])).rows[0].state,'delivered');pass('product receipt is delivery-confirmed and a late queued retry cannot downgrade it');
 await db.query("select public.case_notification_webhook_record($1,$2,'email.sent',$3)",[eventId+'_sent',provider,at]);assert.equal((await db.query('select state from private.case_notification_outbox where delivery_id=$1',[delivery])).rows[0].state,'delivered');pass('out-of-order sent event cannot downgrade confirmed delivery');
 await db.query("select public.case_notification_webhook_record($1,$2,'email.complained',$3)",[eventId+'_complaint',provider,at]);assert.equal((await db.query('select state from private.case_notification_outbox where delivery_id=$1',[delivery])).rows[0].state,'suppressed');assert.equal((await db.query('select count(*)::int n from private.case_notification_suppression where recipient_sha256=$1',[recipient])).rows[0].n,1);pass('complaint suppresses future deliveries to this hashed recipient');
 await assert.rejects(web.query('select * from public.case_notification_outbox_claim($1)',[w1]),/permission denied/);await assert.rejects(web.query("select public.case_notification_webhook_record('fake',$1,'email.delivered',now())",[provider]),/permission denied/);pass('customer web role cannot claim messages or manufacture provider events');
 fixtureIdentity=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[recipient])).rows[0].id;
 const token=(await db.query("insert into public.case_access_tokens(case_id,identity_id,purpose,token_hash,expires_at,send_state) values($1,$2,'resend',$3,now()+interval '1 day','sent') returning id",[caseId,fixtureIdentity,delivery])).rows[0].id;
 await web.query("select public.case_access_token_mark_send($1,'queued',null)",[token]);assert.equal((await db.query('select send_state from public.case_access_tokens where id=$1',[token])).rows[0].send_state,'sent');pass('late token queue receipt cannot downgrade a sent token');
 const requestId=randomUUID();const reminderId=createHash('sha256').update(caseId+'reminder').digest('hex');
 await db.query('begin');await db.query('create policy notification_proof on public.case_requests for all to tivdoc_dev_migrator using(true) with check(true)');
 await db.query("insert into public.case_requests(id,case_id,code,question,answer_kind,blocking,opened_at,expires_at) values($1,$2,'regular_day_hours_unknown','Synthetic reminder','number',true,now()-interval '3 days',now()+interval '7 days')",[requestId,caseId]);
 await db.query('drop policy notification_proof on public.case_requests');await db.query('commit');
 await worker.query('select public.case_request_sweep(now(),100)');
 await worker.query("select public.case_notification_reminder_enqueue($1,'reminder_48h',$2,$3,$4,$5,$6,now()+interval '1 hour')",[requestId,reminderId,caseId,fixtureIdentity,createHash('sha256').update(caseId+'other').digest('hex'),args[5]]);
 await web.query("select public.case_request_answer($1,$2,'8')",[requestId,caseId]);
 assert.equal((await worker.query('select * from public.case_notification_outbox_claim($1)',[w1])).rowCount,0);assert.equal((await db.query('select state,last_error from private.case_notification_outbox where delivery_id=$1',[reminderId])).rows[0].last_error,'request_resolved');pass('answered queued reminder is cancelled before a provider attempt');
 await db.query('select public.case_access_session_create($1,$2,86400)',[fixtureIdentity,delivery]);
 await db.query("update public.case_access_sessions set last_seen_at=now()-interval '2 days' where session_hash=$1",[delivery]);
 const renewed=(await web.query('select * from public.case_access_session_resolve($1,2592000,86400)',[delivery])).rows[0];
 assert.ok(Date.parse(renewed.expires_at)>Date.now()+29*86400000);pass('actual session renewal returns the extended database expiry used by the cookie');
 await web.query('select public.case_access_session_revoke($1)',[delivery]);assert.equal((await web.query('select * from public.case_access_session_resolve($1,2592000,86400)',[delivery])).rowCount,0);pass('revoked session cannot reopen even when rolling renewal is requested');
 writeFileSync('docs/release-evidence/P07-notification-db.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',fixtures:'synthetic; no message sent',provider_and_DNS_verified:false,production:'untouched'},null,2)+'\n');
}finally{await db.query("delete from public.cases where id=$1 and first_name='Synthetic notification'",[caseId]);await db.query('delete from private.case_notification_webhooks where provider_message_id=$1',[provider]);await db.query('delete from private.case_notification_suppression where recipient_sha256=$1',[recipient]);if(fixtureIdentity)await db.query('delete from public.case_identities where id=$1',[fixtureIdentity]);await Promise.all([db.end(),web.end(),worker.end(),peer.end()]);}
