import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';import {offerSnapshot} from '../../src/server/product/orders/contracts.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString(),connectionTimeoutMillis:15000});}
const db=client('TIVDOC_DEV_DATABASE_URL'),web=client('TIVDOC_WEB_POSTGRES_URL'),peer=client('TIVDOC_WEB_POSTGRES_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL');await Promise.all([db.connect(),web.connect(),peer.connect(),worker.connect()]);
const caseId=randomUUID(),other=randomUUID(),fixture='synthetic-order-proof:'+caseId;let identity:string|undefined;const checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{
 if(!(await db.query("select to_regclass('private.product_orders') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907120000_product_orders.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regclass('private.order_sla') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907121000_order_lifecycle_guards.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regprocedure('public.case_order_funnel_state(uuid)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907122000_order_input_scope.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 for(const id of [caseId,other])await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month,contact_verified_at,is_qa) values($1,'Synthetic order','synthetic@example.invalid','0500000000','documents_uploaded','not_started','2026-06-01',now(),true)",[id]);
 identity=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[createHash('sha256').update(caseId).digest('hex')])).rows[0].id;await db.query('select public.case_access_identity_link($1,$2)',[identity,caseId]);
 await db.query("insert into public.documents(case_id,document_type,slot,storage_path,original_filename,mime_type,size) values($1,'payslip','payslip-01',$2,'synthetic.pdf','application/pdf',100)",[caseId,`cases/${caseId}/synthetic.pdf`]);
 const create=async(kind:'initial'|'full',from='2026-06-01',to='2026-06-01',offer=offerSnapshot(kind))=>(await web.query('select public.case_order_create($1,$2,$3,$4,$5,$6) value',[caseId,identity,kind,from,to,offer])).rows[0].value;
 await assert.rejects(create('initial'),/ORDER_COVERAGE_UNAVAILABLE/);pass('zero deliverable coverage cannot create a sale');
 for(const kind of ['initial','full'])await db.query("insert into private.order_availability(kind,topic,period_from,period_to,ready,evidence_reference) values($1,'minimum_wage','2020-01-01','2030-12-01',true,$2)",[kind,fixture]);
 const initial=await create('initial'),repeat=await create('initial');assert.equal(initial.id,repeat.id);assert.equal(initial.amount_minor,999);const full=await create('full','2024-06-01');assert.notEqual(full.id,initial.id);assert.equal(full.amount_minor,14900);pass('initial and full are independent scope/price snapshots; retries reuse the order');
 await assert.rejects(web.query('select public.case_order_snapshot($1,$2)',[other,identity]),/ORDER_FORBIDDEN/);pass('an identity cannot read another case orders');
 async function begin(order:{id:string;terms_version:string},client=web){return (await client.query('select public.case_order_checkout_begin($1,$2,$3,$4,$5,$6) value',[caseId,identity,order.id,randomUUID(),createHash('sha256').update(randomUUID()).digest('hex'),order.terms_version])).rows[0].value;}
 const claims=await Promise.all([begin(initial),begin(initial,peer)]);assert.equal(claims.filter(c=>c.claimed).length,1);const checkout=claims.find(c=>c.claimed).checkout;pass('double-click and two tabs reserve one provider checkout attempt');
 await web.query("select public.case_order_checkout_finish($1,$2,'synthetic-log-initial',null,'https://synthetic.invalid/checkout',null)",[initial.id,checkout.attempt_id]);
 await assert.rejects(web.query("select public.case_order_payment_verify($1,'synthetic-log-initial','synthetic-payment-initial','confirmed',999,'ILS')",[initial.id]),/permission denied/);pass('customer server role cannot manufacture payment verification');
 for(const amount of [null,998])await assert.rejects(worker.query("select public.case_order_payment_verify($1,'synthetic-log-initial','synthetic-payment-initial','confirmed',$2,'ILS')",[initial.id,amount]),/ORDER_PAYMENT_MISMATCH/);pass('null or wrong amount cannot grant entitlement');
 assert.equal((await worker.query("select public.case_order_payment_verify($1,'synthetic-log-initial','synthetic-payment-initial','confirmed',999,'ILS') value",[initial.id])).rows[0].value,true);assert.equal((await worker.query("select public.case_order_payment_verify($1,'synthetic-log-initial','synthetic-payment-initial','confirmed',999,'ILS') value",[initial.id])).rows[0].value,false);assert.equal((await db.query('select count(*)::int n from private.order_entitlements where order_id=$1',[initial.id])).rows[0].n,1);pass('verified provider observation grants one entitlement across replay');
 await db.query("update public.cases set status='completed' where id=$1",[caseId]);const fullAttempt=await begin(full);await web.query("select public.case_order_checkout_finish($1,$2,'synthetic-log-full',null,'https://synthetic.invalid/full',null)",[full.id,fullAttempt.checkout.attempt_id]);
 await assert.rejects(worker.query("select public.case_order_payment_verify($1,'synthetic-log-full','synthetic-payment-initial','confirmed',14900,'ILS')",[full.id]),/duplicate key/);pass('one provider charge cannot fund two orders even in the same case');
 await worker.query("select public.case_order_payment_verify($1,'synthetic-log-full','synthetic-payment-full','confirmed',14900,'ILS')",[full.id]);assert.equal((await db.query('select status from public.cases where id=$1',[caseId])).rows[0].status,'completed');pass('paying for the full order preserves the initial case status');
 const changed={...offerSnapshot('full'),amount_minor:19900};assert.equal((await create('full','2024-06-01','2026-06-01',changed)).amount_minor,14900);const future=await create('full','2025-06-01','2026-06-01',changed);assert.equal(future.amount_minor,19900);const pending=await begin(future);await web.query("select public.case_order_checkout_finish($1,$2,null,null,null,'provider_unavailable')",[future.id,pending.checkout.attempt_id]);assert.equal((await begin(future)).claimed,false);pass('price changes affect new orders only; unknown provider outcome never creates a second checkout');
 await assert.rejects(db.query("update private.product_orders set amount_minor=10 where id=$1",[initial.id]),/ORDER_QUOTE_IMMUTABLE/);pass('saved price and scope cannot be edited after creation');
 const sla=(await web.query('select public.case_order_sla_snapshot($1,$2) value',[caseId,identity])).rows[0].value;assert.equal(sla.length,2);assert.ok(sla.every((v:{started_at:string;budget_ms:number})=>v.started_at&&v.budget_ms>0));pass('verified orders start independent persisted service clocks');
 const refundArgs=[caseId,identity,full.id,randomUUID(),'Synthetic cancellation request'];assert.equal((await web.query('select public.case_order_refund_request($1,$2,$3,$4,$5) value',refundArgs)).rows[0].value,'requested');await web.query('select public.case_order_refund_request($1,$2,$3,$4,$5)',refundArgs);assert.equal((await db.query('select count(*)::int n from private.order_refund_requests where order_id=$1',[full.id])).rows[0].n,1);assert.equal((await db.query('select state from private.order_entitlements where order_id=$1',[full.id])).rows[0].state,'active');pass('refund retry records one request, never asserts refunded or revokes delivery');
 const journal=(await db.query('select input from private.case_input_versions where case_id=$1 order by revision desc limit 1',[caseId])).rows[0].input;assert.equal(journal.orders.length,2);pass('paid order scope participates in the immutable analysis input');
 const clocks=(await web.query('select public.case_order_sla_snapshot($1,$2) value',[caseId,identity])).rows[0].value;
 assert.equal(clocks.length,2);assert.ok(clocks.every((c:{started_at:string;calendar:{version:string};budget_ms:number})=>Number.isFinite(Date.parse(c.started_at))&&c.calendar.version==='tivdoc-service-calendar-2026-v1'&&Number(c.budget_ms)>0));pass('authenticated order clocks retain distinct verified-payment start, saved calendar and positive budget');
 await assert.rejects(()=>web.query('select public.case_order_sla_snapshot($1,$2)',[other,identity]),/ORDER_FORBIDDEN/);pass('order clocks reject an identity requesting another case');
 writeFileSync('docs/release-evidence/P09-orders-db.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',fixtures:'synthetic QA; fake provider coordinates, no external charge',provider_verified:false,production:'untouched'},null,2)+'\n');
}finally{await db.query("delete from public.cases where id=any($1::uuid[]) and first_name='Synthetic order'",[[caseId,other]]);await db.query('delete from private.order_availability where evidence_reference=$1',[fixture]);if(identity)await db.query('delete from public.case_identities where id=$1',[identity]);await Promise.all([db.end(),web.end(),peer.end(),worker.end()]);}
