import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString()});}
const db=client('TIVDOC_DEV_DATABASE_URL'),web=client('TIVDOC_WEB_POSTGRES_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL');await Promise.all([db.connect(),web.connect(),worker.connect()]);
const id=randomUUID(),other=randomUUID(),requestId=randomUUID(),sessionHash=createHash('sha256').update(randomUUID()).digest('hex');let identity:string|undefined;const checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{
 for(const [table,file] of [['private.privacy_requests','20260907130000_privacy_requests.sql'],['private.storage_gc_candidates','20260907131000_storage_gc_fence.sql']])if(!(await db.query('select to_regclass($1) value',[table])).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/'+file,'utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regprocedure('public.case_privacy_queue()') value")).rows[0].value)await db.query(readFileSync('supabase/migrations/20260907132000_privacy_operations_sweep.sql','utf8'));
 if(!(await db.query("select to_regclass('private.privacy_cleanup_events') value")).rows[0].value)await db.query(readFileSync('supabase/migrations/20260907133000_retention_hold_serialization.sql','utf8'));
 for(const caseId of [id,other])await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month,contact_verified_at,is_qa) values($1,'Synthetic privacy','synthetic@example.invalid','0500000000','documents_uploaded','not_started','2026-06-01',now(),true)",[caseId]);
 identity=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[createHash('sha256').update(id).digest('hex')])).rows[0].id;await db.query('select public.case_access_identity_link($1,$2)',[identity,id]);await web.query('select public.case_access_session_create($1,$2,3600)',[identity,sessionHash]);const session=(await db.query('select id from public.case_access_sessions where session_hash=$1',[sessionHash])).rows[0].id;
 const args=[requestId,identity,id,'deletion','Synthetic deletion request'];await web.query('select public.case_privacy_request($1,$2,$3,$4,$5)',args);await web.query('select public.case_privacy_request($1,$2,$3,$4,$5)',args);assert.equal((await db.query('select count(*)::int n from private.privacy_requests where id=$1',[requestId])).rows[0].n,1);pass('privacy request retry preserves one pending request without deleting data');
 await assert.rejects(web.query('select public.case_privacy_request($1,$2,$3,$4,$5)',[randomUUID(),identity,other,'access','Synthetic access request']),/PRIVACY_FORBIDDEN/);await assert.rejects(web.query('select public.case_privacy_export($1,$2,$3)',[other,identity,session]),/PRIVACY_FORBIDDEN/);pass('cross-case request and export are refused');
 const data=(await web.query('select public.case_privacy_export($1,$2,$3) value',[id,identity,session])).rows[0].value;assert.equal(data.case.first_name,'Synthetic privacy');assert.ok(!JSON.stringify(data).includes(sessionHash));assert.ok(!JSON.stringify(data).includes('storage_path'));pass('fresh-session export returns owner data without session secrets or storage coordinates');
 await db.query("update public.case_access_sessions set created_at=now()-interval '16 minutes' where id=$1",[session]);await assert.rejects(web.query('select public.case_privacy_export($1,$2,$3)',[id,identity,session]),/PRIVACY_REAUTH_REQUIRED/);pass('rolling session does not bypass fresh authentication for export');
 const doc=randomUUID(),version=randomUUID(),path=`cases/${id}/versions/${version}.pdf`;await db.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',100)",[doc,id,version,path]);
 assert.equal((await worker.query("select public.case_documents_gc_mark($1,now()-interval '100 days') value",[path])).rows[0].value,'retained:current_document');pass('GC retains a live document even after the nominal retention period');
 const orphan=`cases/${id}/versions/${randomUUID()}.pdf`;await assert.rejects(web.query('select public.case_documents_gc_mark($1,now())',[orphan]),/permission denied/);pass('customer server role cannot invoke storage deletion protocol');
 assert.equal((await worker.query("select public.case_documents_gc_mark($1,now()-interval '100 days') value",[orphan])).rows[0].value,'marked');assert.equal((await worker.query('select public.case_documents_gc_claim($1) value',[orphan])).rows[0].value,'not_due');pass('old orphan is marked but cannot bypass the deletion grace window');
 await db.query("update private.storage_gc_candidates set eligible_at=now()-interval '1 second' where path=$1",[orphan]);assert.equal((await worker.query('select public.case_documents_gc_claim($1) value',[orphan])).rows[0].value,'deleting');await assert.rejects(web.query("update public.documents set storage_path=$1 where id=$2",[orphan,doc]),/GC_OBJECT_RETIRED/);pass('durable GC fence rejects a new reference before any storage remove');
 await assert.rejects(db.query("insert into private.case_retention_holds(case_id,reason,evidence_reference,review_at) values($1,'integrity_investigation','synthetic',now()+interval '1 day')",[id]),/RETENTION_GC_IN_PROGRESS/);pass('a late hold cannot claim protection while object removal is in flight');
 assert.equal((await worker.query('select public.case_documents_gc_claim($1) value',[orphan])).rows[0].value,'deleting');await worker.query('select public.case_documents_gc_finish($1)',[orphan]);assert.equal((await worker.query('select public.case_documents_gc_claim($1) value',[orphan])).rows[0].value,'deleted');assert.equal((await db.query('select storage_path from public.documents where id=$1',[doc])).rows[0].storage_path,path);pass('crash/retry preserves the fence and cannot alter the live document');
 const hold=randomUUID();await db.query("insert into private.case_retention_holds(id,case_id,reason,evidence_reference,review_at) values($1,$2,'integrity_investigation','synthetic retention proof',now()+interval '1 day')",[hold,id]);
 const heldPath=`cases/${id}/versions/${randomUUID()}.pdf`;assert.equal((await worker.query("select public.case_documents_gc_mark($1,now()-interval '100 days') value",[heldPath])).rows[0].value,'retained:retention_hold');pass('a committed hold protects even an otherwise eligible orphan');
 const draftRequest=randomUUID();await worker.query("insert into public.case_requests(id,case_id,code,question,answer_kind,blocking,opened_at,expires_at,expired_at) values($1,$2,'synthetic.privacy','Synthetic draft question','text',false,now()-interval '50 days',now()-interval '40 days',now()-interval '40 days')",[draftRequest,id]);await db.query("insert into private.case_request_drafts(request_id,identity_id,revision,answer_text,updated_at) values($1,$2,1,'Synthetic preserved draft',now()-interval '40 days')",[draftRequest,identity]);
 await worker.query('select public.case_privacy_draft_sweep(100)');assert.equal((await db.query('select count(*)::int n from private.case_request_drafts where request_id=$1',[draftRequest])).rows[0].n,1);
 await db.query('update private.case_retention_holds set released_at=now() where id=$1',[hold]);await worker.query('select public.case_privacy_draft_sweep(100)');assert.equal((await db.query('select count(*)::int n from private.case_request_drafts where request_id=$1',[draftRequest])).rows[0].n,0);assert.equal((await db.query("select count(*)::int n from private.privacy_cleanup_events where request_sha256=encode(sha256(convert_to($1,'UTF8')),'hex')",[draftRequest])).rows[0].n,1);await worker.query('select public.case_privacy_draft_sweep(100)');pass('terminal draft cleanup respects holds and writes one audit event across retries');
 writeFileSync('docs/release-evidence/P10-privacy-db.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',fixtures:'synthetic QA',storage_bytes_deleted:false,production:'untouched'},null,2)+'\n');
}finally{await db.query('delete from private.case_retention_holds where case_id=any($1::uuid[])',[[id,other]]);await db.query('delete from private.privacy_request_events where request_id=$1',[requestId]);await db.query('delete from private.privacy_requests where id=$1',[requestId]);await db.query('delete from private.storage_gc_candidates where case_id=any($1::uuid[])',[[id,other]]);await db.query("delete from public.cases where id=any($1::uuid[]) and first_name='Synthetic privacy'",[[id,other]]);if(identity)await db.query('delete from public.case_identities where id=$1',[identity]);await Promise.all([db.end(),web.end(),worker.end()]);}
