import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash,randomUUID} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {SUPABASE_ROOT_2021_CA} from '../../src/server/product/case-access/supabase-ca.ts';
const env=readDevEnvFile();function client(key:string){const u=new URL(env.get(key)!);assert.equal(u.pathname,'/tivdoc_release_replay_20260907');assert.equal(u.hostname,'aws-0-eu-central-1.pooler.supabase.com');assert.ok(u.username.endsWith('.cpzrbidxftzqcfeqqusu'));u.search='';return new pg.Client({connectionString:u.toString(),ssl:{rejectUnauthorized:true,ca:SUPABASE_ROOT_2021_CA}});}
const db=client('TIVDOC_DEV_DATABASE_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL'),ids=[randomUUID(),randomUUID()],checks:string[]=[];
const sql=readFileSync('supabase/migrations/20260907193000_questionnaire_source_scope.sql','utf8');
try{await db.connect();await worker.connect();await db.query('begin');await db.query(sql);await db.query('commit');
 await db.query('begin');for(const id of ids)await db.query("insert into public.cases(id,first_name,email,phone,is_qa,status,payment_status,check_period_month) values($1,'Synthetic questionnaire scope','qa@example.invalid','0500000000',true,'under_review','verified','2026-08-01')",[id]);
 const q=(await db.query("insert into public.questionnaire_responses(case_id,payload,suspected_issue) values($1,$2,'') returning id",[ids[0],{salaryType:'hourly',employmentStartMonth:'2024-07',managerialOrTrustRole:true}])).rows[0].id;await db.query('commit');
 const read=async()=>{const row=(await worker.query('select v.input,v.input_sha256,v.revision from private.case_input_versions v join private.case_input_heads h on h.case_id=v.case_id and h.revision=v.revision where v.case_id=$1',[ids[0]])).rows[0];assert.ok(row);return row;};
 const before=await read();assert.equal(before.input.questionnaire_source.id,q);assert.equal(before.input.questionnaire_source.case_id,ids[0]);assert.equal(before.input.questionnaire_source.scope_month,'2026-08');assert.equal(before.input.questionnaire.salaryType,'hourly');checks.push('actual worker reads questionnaire identity, exact payload and original check-month scope in saved journal');
 await db.query("update public.cases set check_period_month='2026-07-01' where id=$1",[ids[0]]);const moved=await read();assert.equal(moved.input.month,'2026-07');assert.equal(moved.input.questionnaire_source.scope_month,'2026-08');assert.notEqual(moved.input_sha256,before.input_sha256);checks.push('changing checked month does not extend old declarations to that month');
 await db.query("update public.questionnaire_responses set payload=payload||'{\"salaryType\":\"monthly\"}'::jsonb where id=$1",[q]);const corrected=await read();assert.equal(corrected.input.questionnaire.salaryType,'monthly');assert.equal(corrected.input.questionnaire_source.id,q);
 const old=(await worker.query('select input,input_sha256 from private.case_input_versions where case_id=$1 and revision=$2',[ids[0],before.revision])).rows[0];assert.deepEqual(old.input,before.input);assert.equal(old.input_sha256,before.input_sha256);checks.push('payload update creates a new input revision while the prior payload and hash remain exact');
 await assert.rejects(db.query('update public.questionnaire_responses set case_id=$2 where id=$1',[q,ids[1]]),/QUESTIONNAIRE_SCOPE_IMMUTABLE/);await assert.rejects(db.query("update public.questionnaire_responses set statement_month='2026-07-01' where id=$1",[q]),/QUESTIONNAIRE_SCOPE_IMMUTABLE/);checks.push('case reassignment and statement-period rewrite both refused by DB');
 await assert.rejects(worker.query("update public.questionnaire_responses set payload='{}' where id=$1",[q]),/permission denied/);checks.push('worker cannot rewrite customer questionnaire');
 await db.query('delete from public.cases where id=any($1::uuid[]) and is_qa and first_name=$2',[ids,'Synthetic questionnaire scope']);assert.equal(Number((await db.query('select count(*) n from public.cases where id=any($1::uuid[])',[ids])).rows[0].n),0);
 writeFileSync('docs/release-evidence/P05-questionnaire-source-db.json',JSON.stringify({database:'tivdoc_release_replay_20260907',migration:'20260907193000_questionnaire_source_scope.sql',migration_sha256:createHash('sha256').update(sql).digest('hex'),checks,syntheticFixturesRemoved:2,scope:'Actual DB journal + worker read; no provider invocation or end-to-end analysis claimed',productionChanged:false},null,2)+'\n');console.log({checks});
}finally{await db.query('rollback').catch(()=>{});await db.query('delete from public.cases where id=any($1::uuid[]) and is_qa and first_name=$2',[ids,'Synthetic questionnaire scope']).catch(()=>{});await Promise.all([db.end(),worker.end()]);}
