import '../production-refusal.mjs';
import {offerSnapshot} from '../../src/server/product/orders/contracts.ts';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';
import {canonicalSha256} from '../../src/engine/rule-runtime/canonical.ts';
import {S04_HIGH_CERTAINTY} from '../../src/server/product/reports/case-report-projection.fixtures.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);
function client(key:string){const u=new URL(env.get(key)!);u.pathname='/tivdoc_release_replay_20260907';return new pg.Client({connectionString:u.toString(),connectionTimeoutMillis:15000});}
const db=client('TIVDOC_DEV_DATABASE_URL'),ops=client('TIVDOC_OPERATIONS_POSTGRES_URL'),web=client('TIVDOC_WEB_POSTGRES_URL'),worker=client('TIVDOC_WORKER_POSTGRES_URL');await Promise.all([db.connect(),ops.connect(),web.connect(),worker.connect()]);
const caseId=randomUUID(),other=randomUUID(),projectionId=randomUUID();const checks:string[]=[];let fixtureIdentity:string|undefined;
const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{
 if(!(await db.query("select to_regprocedure('public.case_report_qa_detail(uuid)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907103000_report_review_binding.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regprocedure('public.case_report_source(uuid,uuid,uuid,uuid)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907104500_report_customer_artifacts.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regclass('private.case_report_delivery') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907105500_report_delivery_intentions.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select to_regprocedure('public.case_report_qa_source(uuid,uuid)') value")).rows[0].value){await db.query('begin');try{await db.query(readFileSync('supabase/migrations/20260907110000_report_review_sources.sql','utf8'));await db.query('commit');}catch(e){await db.query('rollback');throw e;}}
 if(!(await db.query("select pg_get_functiondef('private.case_report_current_input()'::regprocedure) value")).rows[0].value.includes('REPORT_PROVENANCE_REQUIRED'))await db.query(readFileSync('supabase/migrations/20260907111000_report_provenance_publication.sql','utf8'));
 await db.query(readFileSync('supabase/migrations/20260907123000_report_order_entitlement.sql','utf8'));
 await db.query('begin');
 for(const id of [caseId,other])await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month) values($1,'Synthetic review','synthetic@example.invalid','0500000000','under_review','verified','2026-06-01')",[id]);
 await db.query("update public.cases set payment_status='verified' where id=$1",[caseId]);
 await db.query('create policy review_proof on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');
 const publicId=(await db.query('select public_id from public.cases where id=$1',[caseId])).rows[0].public_id;
 const projection={...S04_HIGH_CERTAINTY,case_public_id:publicId};
 const docId=randomUUID(),versionId=randomUUID(),evidenceId=randomUUID();
 await db.query('create policy review_document_proof on public.documents for all to tivdoc_dev_migrator using(true) with check(true)');
 await db.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size,content_sha256) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',100,$5)",[docId,caseId,versionId,`cases/${caseId}/versions/${versionId}.pdf`,'b'.repeat(64)]);
 await db.query('drop policy review_document_proof on public.documents');
 const orderId=randomUUID(),offer=offerSnapshot('initial');await db.query("insert into private.product_orders(id,case_id,kind,period_from,period_to,amount_minor,currency,offer,offer_sha256,topics,terms_version,state,verified_at) values($1,$2,'initial','2026-06-01','2026-06-01',999,'ILS',$3,$4,array['minimum_wage'], $5,'paid',now())",[orderId,caseId,offer,offer.sha256,offer.terms_version]);await db.query("insert into private.order_entitlements(order_id,state) values($1,'active')",[orderId]);
 const input=(await db.query('select * from private.case_input_heads where case_id=$1',[caseId])).rows[0];
 const document={schema_version:'tivdoc-report-document-v2',id:projectionId,case_id:caseId,order_id:orderId,revision:1,input_sha256:input.input_sha256,projection_sha256:canonicalSha256(projection),purchased_period:{from:'2026-06',to:'2026-06'},projection,evidence:[{id:evidenceId,document_id:docId,version_id:versionId,sha256:'b'.repeat(64),page:1,field:'gross',fact_version:'1'}],findings:[{id:randomUUID(),topic:'minimum_wage',evidence_ids:[evidenceId],rule_versions:['synthetic-rule'],parameter_versions:['synthetic-parameter']}],publication:{state:'draft',approved_input_sha256:null,approval_actor_kind:null,published_at:null},correction_policy:'append_new_revision_preserve_published'};

 await db.query("insert into public.case_report_projections(id,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,generated_at,input_revision) values($1,$2,$3,'initial','2026-06-01',$4,$5,$6,now(),$7)",[projectionId,caseId,projection.schema_version,projection,canonicalSha256(projection),projection.legal_basis,input.revision]);
 await db.query('update public.case_report_projections set report_document=$1 where id=$2',[document,projectionId]);
 await db.query('drop policy review_proof on public.case_report_projections');await db.query('commit');
 const q=(await ops.query("select * from public.case_report_qa_enqueue($1,$2,'initial','human',array['document_not_automatic_track'],'queued','system:publication_gate')",[caseId,projectionId])).rows[0];
 const detail=async()=> (await ops.query('select public.case_report_qa_detail($1) value',[q.id])).rows[0].value;
 const fingerprint=(await detail()).fingerprint;assert.match(fingerprint,/^[a-f0-9]{64}$/);pass('actual operations role reads saved preview and review fingerprint');
 await db.query("update private.order_entitlements set state='suspended' where order_id=$1",[orderId]);await assert.rejects(ops.query("select * from public.case_report_qa_decide_bound($1,'approved','operator:synthetic-proof',10,$2)",[q.id,fingerprint]),/REPORT_PAID_ORDER_REQUIRED/);await db.query("update private.order_entitlements set state='active' where order_id=$1",[orderId]);pass('an approved report requires the same case paid active order entitlement');
 await assert.rejects(ops.query("select * from public.case_report_qa_decide_bound($1,'published','operator:synthetic-proof',10,$2)",[q.id,fingerprint]),/REPORT_APPROVAL_REQUIRED/);pass('direct publication without approval is refused');
 await ops.query("select * from public.case_report_qa_wording_set($1,$2,'operator:synthetic-proof')",[q.id,{minimum_wage:'נבקש לברר את בסיס הנתונים ששימש לבדיקה.'}]);
 await assert.rejects(ops.query("select * from public.case_report_qa_decide_bound($1,'approved','operator:synthetic-proof',10,$2)",[q.id,fingerprint]),/REPORT_REVIEW_STALE/);pass('wording changes invalidate the previously viewed fingerprint');
 const updated=(await detail()).fingerprint;await ops.query("select * from public.case_report_qa_decide_bound($1,'approved','operator:synthetic-proof',10,$2)",[q.id,updated]);
 await assert.rejects(worker.query("select * from public.case_report_qa_decide_bound($1,'approved','operator:synthetic-proof',10,$2)",[q.id,updated]),/permission denied/);await assert.rejects(web.query('select public.case_report_qa_detail($1)',[q.id]),/permission denied/);pass('worker cannot impersonate a human review; customer role cannot read QA');
 await ops.query("select * from public.case_report_qa_decide_bound($1,'published','operator:synthetic-proof',10,$2)",[q.id,updated]);const publishedAt=(await detail()).row.published_at;
 await ops.query("select * from public.case_report_qa_decide_bound($1,'published','operator:synthetic-proof',10,$2)",[q.id,updated]);assert.equal((await detail()).row.published_at,publishedAt);pass('publication retry preserves the first publication and receipt');
 assert.equal((await db.query('select count(*)::int n from private.case_report_delivery where report_id=$1',[projectionId])).rows[0].n,1);pass('publication and one delivery intention commit together across retries');
 await db.query('begin');await db.query('create policy review_proof on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');await db.query('savepoint mutate');
 await assert.rejects(db.query('update public.case_report_projections set projection_sha256=$1 where id=$2',['b'.repeat(64),projectionId]),/REPORT_APPEND_REVISION_REQUIRED/);await db.query('rollback');pass('approved/published source envelope cannot be overwritten');
 fixtureIdentity=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[caseId.replaceAll('-','').repeat(2)])).rows[0].id;await db.query('select public.case_access_identity_link($1,$2)',[fixtureIdentity,caseId]);
 await db.query("update public.cases set check_period_month='2026-07-01' where id=$1",[caseId]);
 assert.equal((await web.query('select public.case_report_customer_snapshot($1,$2) value',[caseId,fixtureIdentity])).rows[0].value.reports.length,1);
 await assert.rejects(web.query('select public.case_report_customer_snapshot($1,$2)',[other,fixtureIdentity]),/REPORT_FORBIDDEN/);pass('input change preserves published history, scoped to its owner');
 const secondId=randomUUID();await db.query('begin');await db.query('create policy review_proof on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');await db.query("insert into public.case_report_projections(id,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,generated_at,input_revision,report_document) select $1,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,now(),1,jsonb_set(report_document,'{id}',to_jsonb($1::uuid::text)) from public.case_report_projections where id=$2",[secondId,projectionId]);await db.query('drop policy review_proof on public.case_report_projections');await db.query('commit');
 const stale=(await ops.query("select * from public.case_report_qa_enqueue($1,$2,'initial','human',array['document_not_automatic_track'],'queued','system:publication_gate')",[caseId,secondId])).rows[0];const staleHash=(await ops.query('select public.case_report_qa_detail($1) value',[stale.id])).rows[0].value.fingerprint;
 await assert.rejects(ops.query("select * from public.case_report_qa_decide_bound($1,'approved','operator:synthetic-proof',10,$2)",[stale.id,staleHash]),/REPORT_PROVENANCE_REQUIRED|REPORT_INPUT_STALE/);pass('stale saved input cannot receive a new approval');
 writeFileSync('docs/release-evidence/P08-report-review-db.json',JSON.stringify({checks,database:'tivdoc_release_replay_20260907',fixtures:'synthetic; role behavior only, no human attestation',provider_delivery:false,production:'untouched'},null,2)+'\n');
}finally{await db.query('rollback').catch(()=>{});await db.query('begin');try{await db.query('create policy review_proof on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');await db.query('create policy review_qa_proof on public.case_report_qa for all to tivdoc_dev_migrator using(true) with check(true)');await db.query('create policy review_log_proof on public.case_report_qa_log for all to tivdoc_dev_migrator using(true) with check(true)');await db.query('alter table public.case_report_qa_log disable trigger case_report_qa_log_no_update');await db.query("delete from public.cases where id=any($1::uuid[]) and first_name='Synthetic review'",[[caseId,other]]);if(fixtureIdentity)await db.query('delete from public.case_identities where id=$1',[fixtureIdentity]);await db.query('alter table public.case_report_qa_log enable trigger case_report_qa_log_no_update');for(const [table,policy] of [['case_report_projections','review_proof'],['case_report_qa','review_qa_proof'],['case_report_qa_log','review_log_proof']])await db.query(`drop policy ${policy} on public.${table}`);await db.query('commit');}catch(e){await db.query('rollback');throw e;}finally{await Promise.all([db.end(),ops.end(),web.end(),worker.end()]);}}
