import '../production-refusal.mjs';
import {offerSnapshot} from '../../src/server/product/orders/contracts.ts';
import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';import {S04_HIGH_CERTAINTY} from '../../src/server/product/reports/case-report-projection.fixtures.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);const url=new URL(env.get('TIVDOC_DEV_DATABASE_URL')!);url.pathname='/tivdoc_release_replay_20260907';const db=new pg.Client({connectionString:url.toString()});await db.connect();const checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
try{await db.query('begin');for(const [table,policy] of [['documents','source_doc_proof'],['document_versions','source_version_proof'],['case_report_projections','source_report_proof'],['case_report_qa','source_qa_proof']])await db.query(`create policy ${policy} on public.${table} for all to tivdoc_dev_migrator using(true) with check(true)`);
 const caseId=randomUUID(),other=randomUUID(),reportId=randomUUID(),documentId=randomUUID(),version=randomUUID(),newVersion=randomUUID(),finding=randomUUID(),identity=randomUUID(),feedback=randomUUID();
 for(const id of [caseId,other])await db.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month) values($1,'Synthetic source','synthetic@example.invalid','0500000000','under_review','verified','2026-06-01')",[id]);
 const created=(await db.query("select public.case_access_identity_upsert('email',$1,'synthetic@example.invalid') id",[identity.replaceAll('-','').repeat(2)])).rows[0].id;await db.query('select public.case_access_identity_link($1,$2)',[created,caseId]);
 await db.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size,content_sha256) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',100,$5)",[documentId,caseId,newVersion,`cases/${caseId}/versions/${newVersion}.pdf`,'b'.repeat(64)]);
 await db.query("insert into public.document_versions(version_id,document_id,case_id,storage_path,original_filename,mime_type,size) values($1,$2,$3,$4,'old-synthetic.pdf','application/pdf',100)",[version,documentId,caseId,`cases/${caseId}/versions/${version}.pdf`]);
 const orderId=randomUUID(),offer=offerSnapshot('initial');await db.query("insert into private.product_orders(id,case_id,kind,period_from,period_to,amount_minor,currency,offer,offer_sha256,topics,terms_version,state,verified_at) values($1,$2,'initial','2026-06-01','2026-06-01',999,'ILS',$3,$4,array['minimum_wage'], $5,'paid',now())",[orderId,caseId,offer,offer.sha256,offer.terms_version]);await db.query("insert into private.order_entitlements(order_id,state) values($1,'active')",[orderId]);
 const projection={...S04_HIGH_CERTAINTY,case_public_id:(await db.query('select public_id from public.cases where id=$1',[caseId])).rows[0].public_id};const evidenceId=randomUUID();const document={schema_version:'tivdoc-report-document-v2',case_id:caseId,id:reportId,order_id:orderId,revision:1,purchased_period:{from:'2026-06',to:'2026-06'},input_sha256:(await db.query('select input_sha256 from private.case_input_heads where case_id=$1',[caseId])).rows[0].input_sha256,projection,projection_sha256:'a'.repeat(64),evidence:[{id:evidenceId,version_id:version,document_id:documentId,sha256:'a'.repeat(64)}],findings:[{id:finding,topic:'minimum_wage',evidence_ids:[evidenceId]}]};
 await db.query("insert into public.case_report_projections(id,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,generated_at,input_revision,report_document) values($1,$2,$3,'initial','2026-06-01',$4,$5,$6,now(),1,$7)",[reportId,caseId,projection.schema_version,projection,'a'.repeat(64),projection.legal_basis,document]);
 await db.query("insert into public.case_report_qa(case_id,projection_id,report_kind,document_track,state,operator_identity,decided_at,published_at) values($1,$2,'initial','automatic','published','system:publication_gate',now(),now())",[caseId,reportId]);
 const source=(await db.query('select public.case_report_source($1,$2,$3,$4) value',[caseId,created,reportId,version])).rows[0].value;assert.equal(source.path,`cases/${caseId}/versions/${version}.pdf`);assert.equal(source.sha256,'a'.repeat(64));pass('saved report resolves its retained old source, never the replacement');
 async function rejected(sql:string,values:unknown[],pattern:RegExp){await db.query('savepoint refusal');await assert.rejects(db.query(sql,values),pattern);await db.query('rollback to savepoint refusal');}
 await rejected('select public.case_report_source($1,$2,$3,$4)',[caseId,created,reportId,newVersion],/REPORT_SOURCE_FORBIDDEN/);await rejected('select public.case_report_source($1,$2,$3,$4)',[other,created,reportId,version],/REPORT_FORBIDDEN/);pass('unreferenced version and foreign case are both refused');
 const args=[feedback,caseId,created,reportId,finding,'Synthetic correction request'];await db.query('select public.case_report_correction_submit($1,$2,$3,$4,$5,$6)',args);await db.query('select public.case_report_correction_submit($1,$2,$3,$4,$5,$6)',args);assert.equal((await db.query('select count(*)::int n from private.case_report_corrections where id=$1',[feedback])).rows[0].n,1);pass('correction retry creates one pending request without changing the report');
 const support=(await db.query('select public.case_request_support_list($1,$2) value',[caseId,created])).rows[0].value;
 assert.equal(support.length,1);assert.equal(support[0].id,feedback);assert.equal(support[0].origin,'finding');assert.equal(support[0].report_id,reportId);assert.equal(support[0].finding_id,finding);assert.equal(support[0].messages.length,1);
 pass('finding correction and its exact report/finding link appear once in the unified customer support thread');

 await rejected('select public.case_report_correction_submit($1,$2,$3,$4,$5,$6)',[feedback,caseId,created,reportId,finding,'Different correction request'],/REPORT_CORRECTION_CONFLICT/);await rejected('select public.case_report_correction_submit($1,$2,$3,$4,$5,$6)',[randomUUID(),other,created,reportId,finding,'Synthetic correction request'],/REPORT_FORBIDDEN/);pass('changed retry and cross-case correction cannot overwrite or attach');
 writeFileSync('docs/release-evidence/P08-support-finding-db.json',JSON.stringify({checks,fixtures:'synthetic rollback transaction; retained source metadata only',storage_bytes_verified:false,database:'tivdoc_release_replay_20260907',production:'untouched'},null,2)+'\n');
}finally{await db.query('rollback');await db.end();}
