// Full backup/restore of an owned synthetic clone; source/production protections stay intact.
import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {spawnSync} from 'node:child_process';import {createHash,randomUUID} from 'node:crypto';import pg from 'pg';import {createClient} from '@supabase/supabase-js';import {PDFDocument,StandardFonts} from 'pdf-lib';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {TIVDOC_DEV_PROJECT_REF} from '../supabase-dev-guard/guard.mts';import {offerSnapshot} from '../../src/server/product/orders/contracts.ts';import {S04_HIGH_CERTAINTY} from '../../src/server/product/reports/case-report-projection.fixtures.ts';import {canonicalSha256} from '../../src/engine/rule-runtime/canonical.ts';
const env=readDevEnvFile();assert.equal(env.get('TIVDOC_DEV_PROJECT_REF'),TIVDOC_DEV_PROJECT_REF);const u=new URL(env.get('TIVDOC_DEV_DATABASE_URL')!);const sourceName='tivdoc_release_replay_20260907',suffix=randomUUID().slice(0,8),snapshotName='tivdoc_backup_'+suffix,restoredName='tivdoc_restore_'+suffix;
function client(database:string){const target=new URL(u);target.pathname='/'+database;return new pg.Client({connectionString:target.toString(),connectionTimeoutMillis:15000});}
const source=client(sourceName),admin=client('postgres');await Promise.all([source.connect(),admin.connect()]);const databaseRole=(await admin.query('select current_user name')).rows[0].name;
const root='output/release-completion/restore/'+suffix;mkdirSync(root,{recursive:true});const bin='C:/dev/tivdoc/salary/.tools/postgresql/17.11-1-signed/bin';for(const [name,hash] of [['pg_dump','ff766351cc88b0ea2bc7b6e365777cb51f792b16000688a378f64124810ffa88'],['pg_restore','ae002028451e79240eaad9838d9eb0b644436a05decb3888468a529bf881ac6c']])assert.equal(createHash('sha256').update(readFileSync(`${bin}/${name}.exe`)).digest('hex'),hash);
const pgEnv={...process.env,PGHOST:u.hostname,PGPORT:u.port||'5432',PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGSSLMODE:'require',PGCONNECT_TIMEOUT:'15'};
const probeCase=randomUUID(),version=randomUUID(),doc=randomUUID(),reportId=randomUUID(),orderId=randomUUID();const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);pdf.addPage([300,200]).drawText('Synthetic Tivdoc restore proof',{x:20,y:100,font,size:12});const bytes=Buffer.from(await pdf.save()),sha=createHash('sha256').update(bytes).digest('hex'),objectPath=`cases/${probeCase}/versions/${version}.pdf`;
let snapshot:pg.Client|undefined,restored:pg.Client|undefined,sourceClosed=false;let forced:{schema:string;name:string;owner:string}[]=[];const checks:string[]=[];const pass=(s:string)=>{checks.push(s);console.log('PASS '+s);};
let storage:ReturnType<typeof createClient>['storage']|undefined;const restoreBucket='tivdoc-restore-'+suffix;let restoreBucketCreated=false;
function command(name:string,args:string[],database:string){const result=spawnSync(bin+'/'+name+'.exe',args,{env:{...pgEnv,PGDATABASE:database},encoding:'utf8',windowsHide:true,timeout:600000});if(result.status!==0){writeFileSync(root+'/'+name+'-error.txt',String(result.stderr).replaceAll(decodeURIComponent(u.password),'[redacted]'));throw new Error(name.toUpperCase()+'_FAILED:'+result.status);}return result.stdout;}
const ident=(s:string)=>'"'+s.replaceAll('"','""')+'"';
async function inventory(db:pg.Client){const tables=(await db.query("select n.nspname schema,c.relname name,pg_get_userbyid(c.relowner) owner,c.relforcerowsecurity forced from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and n.nspname not in ('pg_catalog','information_schema') and n.nspname not like 'pg_%' order by 1,2")).rows;const result=[];for(const t of tables){if(t.owner!==databaseRole)await db.query('set role '+ident(t.owner));try{const row=(await db.query(`select count(*)::int count,encode(sha256(convert_to(coalesce(string_agg(row_to_json(t)::text,E'\\n' order by row_to_json(t)::text),''),'UTF8')),'hex') sha from ${ident(t.schema)}.${ident(t.name)} t`)).rows[0];result.push({...t,...row});}finally{await db.query('reset role');}}return result;}
try{
 await source.query("insert into public.cases(id,first_name,email,phone,status,payment_status,check_period_month,contact_verified_at,is_qa) values($1,'Synthetic restore','synthetic@example.invalid','0500000000','documents_uploaded','not_started','2026-06-01',now(),true)",[probeCase]);
 await source.query("insert into public.documents(id,case_id,version_id,document_type,slot,storage_path,original_filename,mime_type,size,content_sha256) values($1,$2,$3,'payslip','payslip-01',$4,'synthetic.pdf','application/pdf',$5,$6)",[doc,probeCase,version,objectPath,bytes.length,sha]);
 const offer=offerSnapshot('initial');await source.query("insert into private.product_orders(id,case_id,kind,period_from,period_to,amount_minor,currency,offer,offer_sha256,topics,terms_version) values($1,$2,'initial','2026-06-01','2026-06-01',999,'ILS',$3,$4,array['minimum_wage'],$5)",[orderId,probeCase,offer,offer.sha256,offer.terms_version]);
 const projection={...S04_HIGH_CERTAINTY,case_public_id:(await source.query('select public_id from public.cases where id=$1',[probeCase])).rows[0].public_id},input=(await source.query('select * from private.case_input_heads where case_id=$1',[probeCase])).rows[0],evidenceId=randomUUID();
 const document={schema_version:'tivdoc-report-document-v2',id:reportId,case_id:probeCase,order_id:orderId,revision:1,input_sha256:input.input_sha256,projection_sha256:canonicalSha256(projection),purchased_period:{from:'2026-06',to:'2026-06'},projection,evidence:[{id:evidenceId,document_id:doc,version_id:version,sha256:sha,page:1,field:'gross',fact_version:'synthetic-v1'}],findings:[{id:randomUUID(),topic:'minimum_wage',evidence_ids:[evidenceId],rule_versions:['synthetic-rule'],parameter_versions:['synthetic-param']}],publication:{state:'draft',approved_input_sha256:null,approval_actor_kind:null,published_at:null},correction_policy:'append_new_revision_preserve_published'};
 await source.query('create policy restore_probe on public.case_report_projections for all to tivdoc_dev_migrator using(true) with check(true)');try{await source.query("insert into public.case_report_projections(id,case_id,schema_version,report_kind,check_period_month,projection,projection_sha256,legal_basis,generated_at,input_revision,report_document) values($1,$2,$3,'initial','2026-06-01',$4,$5,$6,now(),$7,$8)",[reportId,probeCase,projection.schema_version,projection,canonicalSha256(projection),projection.legal_basis,input.revision,document]);}finally{await source.query('drop policy restore_probe on public.case_report_projections');}
 const keys=spawnSync('npx.cmd',['--yes','supabase','projects','api-keys','--project-ref',TIVDOC_DEV_PROJECT_REF,'--output','json'],{encoding:'utf8',shell:true,windowsHide:true,timeout:30000});assert.equal(keys.status,0,'DEV key lookup failed');const key=JSON.parse(keys.stdout).find((v:{name:string})=>v.name==='service_role')?.api_key;assert.ok(key);storage=createClient(`https://${TIVDOC_DEV_PROJECT_REF}.supabase.co`,key,{auth:{persistSession:false}}).storage;
 assert.equal((await storage.from('salary-documents').upload(objectPath,bytes,{contentType:'application/pdf',upsert:false})).error,null);const download=await storage.from('salary-documents').download(objectPath);assert.ok(download.data);const originalBytes=Buffer.from(await download.data.arrayBuffer());assert.equal(createHash('sha256').update(originalBytes).digest('hex'),sha);writeFileSync(root+'/source.pdf',originalBytes);pass('synthetic source bytes are backed up from real private Storage with matching checksum');
 await source.end();sourceClosed=true;
 const signalClients=[admin];
 for(const key of ['TIVDOC_WEB_POSTGRES_URL','TIVDOC_WORKER_POSTGRES_URL','TIVDOC_OPERATIONS_POSTGRES_URL','TIVDOC_IDENTITY_POSTGRES_URL']){const raw=env.get(key);if(!raw)continue;const maintenance=new URL(raw);maintenance.pathname='/postgres';const connection=new pg.Client({connectionString:maintenance.toString(),connectionTimeoutMillis:15000});await connection.connect();signalClients.push(connection);}
 try{
  const permitted=[];for(const connection of signalClients){const role=(await connection.query('select current_user name')).rows[0].name;permitted.push(role);const rows=(await connection.query('select state from pg_stat_activity where datname=$1 and usename=current_user',[sourceName])).rows;if(rows.some(r=>r.state!=='idle'))throw new Error('RESTORE_SOURCE_HAS_ACTIVE_CLIENT');}
  if((await admin.query('select usename from pg_stat_activity where datname=$1',[sourceName])).rows.some(r=>!permitted.includes(r.usename)))throw new Error('RESTORE_SOURCE_HAS_UNKNOWN_CLIENT');
  // Drain only idle backends owned by this isolated proof's explicit credentials.
  await admin.query('alter database '+ident(sourceName)+' allow_connections false');
  try{for(const connection of signalClients)await connection.query("select pg_terminate_backend(pid) from pg_stat_activity where datname=$1 and usename=current_user and state='idle'",[sourceName]);await admin.query('create database '+ident(snapshotName)+' template '+ident(sourceName));}finally{await admin.query('alter database '+ident(sourceName)+' allow_connections true');}
 }finally{await Promise.all(signalClients.filter(c=>c!==admin).map(c=>c.end()));}
 snapshot=client(snapshotName);await snapshot.connect();
 forced=(await snapshot.query("select n.nspname schema,c.relname name,pg_get_userbyid(c.relowner) owner from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and c.relforcerowsecurity and n.nspname not in ('pg_catalog','information_schema')")).rows;
 // Only this private backup clone relaxes FORCE for its existing table owners.
 for(const t of forced){if(t.owner!==databaseRole)await snapshot.query('set role '+ident(t.owner));try{await snapshot.query(`alter table ${ident(t.schema)}.${ident(t.name)} no force row level security`);}finally{await snapshot.query('reset role');}}
 const before=await inventory(snapshot);const backup=root+'/release.dump';command('pg_dump',['--format=custom','--file',backup],snapshotName);pass('complete schema and data custom-format backup created from the isolated owned clone');
 await admin.query('create database '+ident(restoredName));restored=client(restoredName);await restored.connect();
 await restored.query('create schema private');
 const schemaGrants=(await snapshot.query("select n.nspname schema,a.privilege_type privilege,coalesce(r.rolname,'PUBLIC') grantee from pg_namespace n cross join lateral aclexplode(n.nspacl) a left join pg_roles r on r.oid=a.grantee where n.nspname in ('public','private')")).rows;
 for(const grant of schemaGrants){assert.ok(['USAGE','CREATE'].includes(grant.privilege));await restored.query(`grant ${grant.privilege} on schema ${ident(grant.schema)} to ${grant.grantee==='PUBLIC'?'public':ident(grant.grantee)}`);}
 const contents=command('pg_restore',['--list',backup],restoredName).split('\n').filter(line=>!/^\d+;.* SCHEMA - private /.test(line)).join('\n');const toc=root+'/restore.list';writeFileSync(toc,contents);
 command('pg_restore',['--exit-on-error','--no-comments','--use-list',toc,'--dbname',restoredName,backup],restoredName);const after=await inventory(restored);assert.deepEqual(after,before);pass('all table counts and full row-set checksums match after actual pg_restore');
 const refs=(await restored.query('select d.storage_path,d.content_sha256,p.report_document from public.documents d join public.case_report_projections p on p.case_id=d.case_id where d.id=$1',[doc])).rows[0];assert.equal(refs.storage_path,objectPath);assert.equal(refs.content_sha256,sha);assert.deepEqual(refs.report_document,document);pass('saved draft report provenance and its immutable document coordinates survive restore');
 for(const db of [snapshot,restored])for(const t of forced){if(t.owner!==databaseRole)await db.query('set role '+ident(t.owner));try{await db.query(`alter table ${ident(t.schema)}.${ident(t.name)} force row level security`);}finally{await db.query('reset role');}}
 assert.equal(Number((await restored.query('select count(*) n from pg_class where relforcerowsecurity')).rows[0].n),forced.length);pass('original FORCE RLS protection is restored on every protected table');

 assert.equal((await storage.createBucket(restoreBucket,{public:false})).error,null);restoreBucketCreated=true;assert.equal((await storage.from(restoreBucket).upload(objectPath,readFileSync(root+'/source.pdf'),{contentType:'application/pdf',upsert:false})).error,null);const copied=await storage.from(restoreBucket).download(objectPath);assert.ok(copied.data);assert.equal(createHash('sha256').update(Buffer.from(await copied.data.arrayBuffer())).digest('hex'),sha);pass('backup bytes restore to a separate private bucket with the same path and checksum');
 const receipt={checks,sourceDatabase:sourceName,backupClone:snapshotName,restoredDatabase:restoredName,tableCount:before.length,forcedRlsTables:forced.length,backupSha256:createHash('sha256').update(readFileSync(backup)).digest('hex'),extensionCommentsExcluded:true,reportState:'synthetic unpublished draft',sourceBytes:bytes.length,storageRestore:true,production:'untouched',rpoRtoServiceGuaranteeProven:false};writeFileSync('docs/release-evidence/P10-restore.json',JSON.stringify(receipt,null,2)+'\n');
}catch(error){writeFileSync(root+'/status.json',JSON.stringify({status:'blocked',error:error instanceof Error?error.message:'unknown',checks},null,2));throw error;
}finally{
 if(!sourceClosed)await source.end();const cleanup=client(sourceName);await cleanup.connect();try{await cleanup.query("delete from public.cases where id=$1 and first_name='Synthetic restore'",[probeCase]);}finally{await cleanup.end();}
 if(storage){await storage.from('salary-documents').remove([objectPath]);if(restoreBucketCreated){await storage.from(restoreBucket).remove([objectPath]);await storage.deleteBucket(restoreBucket);}}
 for(const connection of [snapshot,restored])if(connection)for(const t of forced){try{if(t.owner!==databaseRole)await connection.query('set role '+ident(t.owner));await connection.query(`alter table if exists ${ident(t.schema)}.${ident(t.name)} force row level security`);}finally{await connection.query('reset role');}}
 await Promise.all([snapshot?.end(),restored?.end(),admin.end()]);
}
