import '../production-refusal.mjs';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';
import {readDevEnvFile} from '../supabase-dev-guard/dev-credential.mts';import {SUPABASE_ROOT_2021_CA} from '../../src/server/product/case-access/supabase-ca.ts';
const env=readDevEnvFile();function client(key:string){const u=new URL(env.get(key)!);assert.equal(u.pathname,'/tivdoc_release_replay_20260907');assert.equal(u.hostname,'aws-0-eu-central-1.pooler.supabase.com');assert.ok(u.username.endsWith('.cpzrbidxftzqcfeqqusu'));u.search='';return new pg.Client({connectionString:u.toString(),ssl:{rejectUnauthorized:true,ca:SUPABASE_ROOT_2021_CA}});}
const db=client('TIVDOC_DEV_DATABASE_URL'),web=client('TIVDOC_WEB_POSTGRES_URL'),otherWeb=client('TIVDOC_WEB_POSTGRES_URL'),ops=client('TIVDOC_OPERATIONS_POSTGRES_URL');const ids=[randomUUID(),randomUUID()],identities:string[]=[],checks:string[]=[];
const sql=readFileSync('supabase/migrations/20260907200000_owner_support_threads.sql','utf8');
try{await Promise.all([db.connect(),web.connect(),otherWeb.connect(),ops.connect()]);await db.query('begin');await db.query(sql);await db.query('commit');
 for(const id of ids){await db.query("insert into public.cases(id,first_name,email,phone,is_qa,status,payment_status,contact_verified_at,check_period_month) values($1,'Synthetic support proof','qa@example.invalid','0500000000',true,'under_review','verified',now(),'2026-08-01')",[id]);const identity=(await web.query("select public.case_access_identity_upsert('email',$1,$2) id",[createHash('sha256').update(id).digest('hex'),id+'@example.invalid'])).rows[0].id;identities.push(identity);await web.query('select public.case_access_identity_link($1,$2)',[identity,id]);}
 const thread=randomUUID(),args=[thread,ids[0],identities[0],'Synthetic support question'];
 await Promise.all([web.query('select public.case_request_support_open($1,$2,$3,$4)',args),otherWeb.query('select public.case_request_support_open($1,$2,$3,$4)',args)]);
 const list=async()=> (await web.query('select public.case_request_support_list($1,$2) value',[ids[0],identities[0]])).rows[0].value;
 assert.equal((await list()).length,1);assert.equal((await list())[0].messages.length,1);checks.push('two actual web connections concurrently retry one question without duplicate thread or message');
 await assert.rejects(web.query('select public.case_request_support_open($1,$2,$3,$4)',[thread,ids[0],identities[0],'Changed retry']),/SUPPORT_RETRY_CONFLICT/);
 await assert.rejects(web.query('select public.case_request_support_list($1,$2)',[ids[1],identities[0]]),/SUPPORT_FORBIDDEN/);
 await assert.rejects(otherWeb.query('select public.case_request_support_reply($1,$2,$3,$4,$5)',[randomUUID(),thread,ids[1],identities[1],'Foreign thread reply']),/SUPPORT_FORBIDDEN/);checks.push('changed retries, cross-case reads and foreign thread replies are refused');
 await assert.rejects(web.query('select public.case_request_support_queue()'),/permission denied/);await assert.rejects(web.query('select public.case_request_support_owner_reply($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),thread,1,'owner:synthetic','Unauthorized reply','resolved','urgent']),/permission denied/);checks.push('web role has no support queue or owner reply authority');
 const reply=randomUUID(),ownerArgs=[reply,thread,1,'owner:synthetic','Synthetic owner support reply','waiting_customer','urgent'];await ops.query('select public.case_request_support_owner_reply($1,$2,$3,$4,$5,$6,$7)',ownerArgs);await ops.query('select public.case_request_support_owner_reply($1,$2,$3,$4,$5,$6,$7)',ownerArgs);
 let current=(await list())[0];assert.equal(current.state,'waiting_customer');assert.equal(current.messages.length,2);assert.equal(current.messages[1].author_kind,'owner');assert.ok(!('actor' in current.messages[1]));checks.push('owner reply is idempotent, visible to its customer and omits internal actor identity');
 await assert.rejects(ops.query('select public.case_request_support_owner_reply($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),thread,1,'owner:synthetic','Stale owner reply','resolved','normal']),/SUPPORT_REVISION_CONFLICT/);checks.push('stale owner action cannot overwrite a newer conversation');
 const customerReply=randomUUID();await web.query('select public.case_request_support_reply($1,$2,$3,$4,$5)',[customerReply,thread,ids[0],identities[0],'Synthetic follow-up']);current=(await list())[0];assert.equal(current.state,'open');assert.equal(current.messages.length,3);assert.equal(current.revision,3);
 const queue=(await ops.query('select public.case_request_support_queue() value')).rows[0].value;assert.equal(queue.find(t=>t.id===thread).priority,'urgent');checks.push('customer reply reopens the same owner queue thread and preserves priority/history');
 const states=(await db.query('select status,payment_status from public.cases where id=any($1::uuid[])',[ids])).rows;assert.ok(states.every(c=>c.status==='under_review'&&c.payment_status==='verified'));checks.push('support actions do not change case or payment status');
 await db.query('delete from public.cases where id=any($1::uuid[]) and is_qa and first_name=$2',[ids,'Synthetic support proof']);await db.query('delete from public.case_identities where id=any($1::uuid[])',[identities]);
 writeFileSync('docs/release-evidence/P08-support-db.json',JSON.stringify({database:'tivdoc_release_replay_20260907',migration:'20260907200000_owner_support_threads.sql',migration_sha256:createHash('sha256').update(sql).digest('hex'),checks,syntheticCasesRemoved:2,syntheticIdentitiesRemoved:2,scope:'Actual web/operations roles and scoped synthetic cases; owner HTTP identity check has separate local tests. No email or professional approval.',productionChanged:false},null,2)+'\n');console.log({checks});
}finally{await db.query('rollback').catch(()=>{});await db.query('delete from public.cases where id=any($1::uuid[]) and is_qa and first_name=$2',[ids,'Synthetic support proof']).catch(()=>{});if(identities.length)await db.query('delete from public.case_identities where id=any($1::uuid[])',[identities]).catch(()=>{});await Promise.all([db.end(),web.end(),otherWeb.end(),ops.end()]);}
