import {describe,it,expect} from 'vitest';
import {canonicalSha256} from '../../rule-runtime/canonical.ts';
import {documentReviewInputSchema} from '../../document-review/contracts.ts';
import {generateReviewCompletions,parseReviewCompletionInput,resolveReviewCompletion,type ReviewCompletionNeed} from '../../document-review/completions.ts';
import {vacationFixture} from '../product-branch.fixture.ts';
import {buildSyntheticCaseFixture} from '../../case-analysis/synthetic-fixtures.ts';
import {normalizeDocumentEvidence} from '../../extraction/document-evidence/normalization.ts';
import {rawDocumentObservationSchema} from '../../extraction/document-evidence/contracts.ts';
import {createDocumentEvidenceReadingTarget,resolveDocumentEvidenceReading} from '../../extraction/document-evidence/reading.ts';
import {savedNonPayslipEvidenceSchema,type SavedNonPayslipEvidence} from '../../extraction/document-evidence/snapshot.ts';
import {nonPayslipEffectiveReadingSha} from '../../document-review/non-payslip.ts';
import {produceVacationSourceEvidence,vacationSourceReadingDependencies,readVacationSourceProductFacts,vacationSourceFactKey} from './product-source-evidence.ts';
import {evaluateVacationCaseRecipe} from './product-decisions.ts';

const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){
 const input=vacationFixture();input.case_id=uuid(1);input.source_manifest[0].case_id=input.case_id;input.applicability=[];
 const s=input.seniority_year!.source;s.reading='provider_extraction';
 const source=documentReviewInputSchema.parse({schema_version:'document-review-product-v1',case_id:input.case_id,period:input.period,purchased_scope:{order_id:'synthetic-order',receipt_sha256:'a'.repeat(64),origin:'saved_order',topics:['vacation']},documents:[{...input.source_manifest[0],kind:'payslip',label:'Synthetic admitted source',period:input.period,reading_origin:'provider_extraction',reading_sha256:s.reading_receipt_sha256}],checks:[],completion_input:{case_id:input.case_id,period:input.period,documents:[],needs:[],evidence:[]},coverage_gaps:[]});
 const pin={case_id:input.case_id,document_id:s.document_id,version_id:s.version_id,source_sha256:s.file_sha256};
 const completion=parseReviewCompletionInput(source.completion_input);
 source.completion_input={...completion,documents:[{pin,kind:'payslip',period:input.period,review:'partial'}],
  needs:['same_employer_or_workplace','preceding_quarter_full_months'].map((key):ReviewCompletionNeed=>({fact_key:vacationSourceFactKey(key as 'same_employer_or_workplace'|'preceding_quarter_full_months'),kind:'factual',reason:'unknown',required_evidence_kind:'customer_declaration',question:'Synthetic factual question',answer_kind:'choice',options:['כן','לא'],source_pins:[pin],dependent_check_ids:[input.check_prefix+'.pay.expected'],general_question:false}))};
 function answer(key:'same_employer_or_workplace'|'preceding_quarter_full_months',state:'provided'|'unknown'='provided',value:string|null='כן'){
  const current=parseReviewCompletionInput(source.completion_input),request=generateReviewCompletions({...current,previous_answers:[],evidence:[]}).customer_requests.find(r=>r.target.fact_key===vacationSourceFactKey(key))!;
  const requestId=uuid(key==='same_employer_or_workplace'?10:11),prior=source.answer_history.filter(h=>h.receipt.request_id===requestId).at(-1);
  const result=resolveReviewCompletion({request,current,actor:{case_id:input.case_id,identity_id:uuid(20)},answer:{request_id:requestId,revision:(prior?.receipt.answer_revision??0)+1,answered_at:'2026-09-12T00:00:00Z',state,value}});
  if(result.state==='stale')throw Error('fixture stale');source.answer_history.push({request,receipt:result.receipt,original_checks:[]});source.completion_input={...current,previous_answers:[...(current.previous_answers??[]),result.receipt],evidence:[...current.evidence,result.evidence]};
 }
 return {input,source,answer};
}
function pay(f:ReturnType<typeof fixture>){const wage={...f.input.seniority_year!,id:'synthetic.wage',representation:'money_ils' as const,quantity_unit:null,printed_value:'9000.00'};f.input.leave_pay={mode:'hourly_quarter',leave_period:{from:'2026-06-01',to:'2026-06-05'},quarter_period:{from:'2026-03-01',to:'2026-05-31'},wage,recorded:null,leave_calendar_days:null};}
function attendance(f:ReturnType<typeof fixture>,labels=['עבודה','מנוחה שבועית','עבודה']){
 const old=buildSyntheticCaseFixture({fixture_id:'vacation-source-producer',mode:'real'}).stored.documents[0];
 const document={...old,document_id:uuid(40),case_id:f.input.case_id,document_type:'attendance' as const,document_period:null,storage_path:'cases/'+f.input.case_id+'/documents/'+uuid(40)+'/original.pdf'};
 const observations=labels.flatMap((label,i)=>[['row_date','iso_date',`2026-06-0${i+1}`],['source_label','text',label]].map(([semantic,value_kind,raw_value])=>rawDocumentObservationSchema.parse({block_id:'daily',row_id:'r'+i,cell_id:semantic,semantic,value_kind,raw_value,source_label:semantic,unit:null,page:1,locator:'Synthetic daily source '+i+' '+semantic,text_fragment:raw_value,state:'present',confidence:1,warnings:[]})));
 const extraction=normalizeDocumentEvidence({document,physicalPageCount:1,raw:{schema_version:'document-evidence-provider-v1',detected_document_type:'attendance',page_count:1,pages:[{page:1,coverage:'complete',missing_regions:[]}],observations,warnings:[]}});
 let record:SavedNonPayslipEvidence=savedNonPayslipEvidenceSchema.parse({document,product_document_id:uuid(41),checkpoint_result_sha256:'c'.repeat(64),provider_receipt_sha256:'d'.repeat(64),extraction,failure_code:null,readings:[]});
 const sync=()=>{f.source.non_payslip_evidence=[record];const d={case_id:f.input.case_id,document_id:document.document_id,version_id:document.document_id,file_sha256:document.content_sha256,page_count:1,kind:'attendance' as const,label:'Synthetic complete daily register',period:{from:'2026-06-01',to:'2026-06-03'},reading_origin:'provider_extraction' as const,reading_sha256:nonPayslipEffectiveReadingSha(record)};f.source.documents=[f.source.documents[0],d];};
 function identify(except=-1){record={...record,readings:extraction.observations.flatMap((o,i)=>{if(i===except)return [];const target=createDocumentEvidenceReadingTarget({normalized:extraction,productDocumentId:record.product_document_id,checkpointSha256:record.checkpoint_result_sha256!,policyVersion:'saved-document-evidence-v1',month:'2026-06',observationId:o.observation_id});const r=resolveDocumentEvidenceReading({target,currentTarget:target,caseId:f.input.case_id,requestId:uuid(100+i),answerRevision:1,identityId:uuid(20),answeredAt:'2026-09-12T00:00:00Z',answer:{action:'confirm'}});if(r.state!=='current')throw Error('fixture');return [r.reading];})};sync();}
 f.input.annual_basis!.employment_start.value='2026-06-01';f.input.annual_basis!.employment_end.value='2026-06-03';f.input.annual_basis!.covered_through.value='2026-06-03';f.input.annual_basis!.actual_workdays!.printed_value='2';sync();return {identify,get record(){return record;},sync};
}
describe('ordinary vacation source producer, without a customer legal certification',()=>{
 it('exposes only factual questions and names absent source producers as software gaps',()=>{const f=fixture(),r=produceVacationSourceEvidence(f.input,f.source);expect(r.evidence.entries).toEqual([]);expect(r.factual_questions.map(q=>q.fact_key)).toEqual([vacationSourceFactKey('same_employer_or_workplace')]);expect(r.software_gaps).toContain('ordinary_leave_period_and_wage_source_producer_missing');expect(r.publication_authority).toBe(false);expect(r.factual_questions.every(q=>q.required_evidence_kind==='customer_declaration')).toBe(true);});
 it('reuses an already accepted provider year without asking for a numeric confirmation',()=>{const f=fixture();f.answer('same_employer_or_workplace');const before=canonicalSha256(f.input),r=produceVacationSourceEvidence(f.input,f.source);expect(r.evidence.entries[0]).toMatchObject({kind:'seniority',source:{reading:'provider_extraction'}});expect(r.factual_questions).toEqual([]);expect(evaluateVacationCaseRecipe('vacation.seniority_basis',f.input,{review:f.source,evidence:r.evidence,authenticated_evidence_sha256s:r.authenticated_evidence_sha256s}).allowed).toBe(true);expect(canonicalSha256(f.input)).toBe(before);});
 it('keeps the answer a declaration and changes only its own evidence on unknown correction',()=>{const f=fixture();pay(f);f.answer('same_employer_or_workplace');f.answer('preceding_quarter_full_months');const before=produceVacationSourceEvidence(f.input,f.source);f.answer('same_employer_or_workplace','unknown',null);const after=produceVacationSourceEvidence(f.input,f.source);expect(readVacationSourceProductFacts(f.source).same_employer_or_workplace.state).toBe('unknown');expect(after.evidence.entries.some(e=>e.kind==='seniority')).toBe(false);expect(after.evidence.entries.find(e=>e.kind==='quarter_selection')).toEqual(before.evidence.entries.find(e=>e.kind==='quarter_selection'));expect(after.factual_questions).toEqual([]);expect(f.source.answer_history).toHaveLength(3);});
 it('does not select an alternative quarter when the factual full-months answer is false',()=>{const f=fixture();pay(f);f.answer('preceding_quarter_full_months','provided','לא');expect(produceVacationSourceEvidence(f.input,f.source).evidence.entries.some(e=>e.kind==='quarter_selection')).toBe(false);});
 it('refuses tampered answer hashes and foreign cases',()=>{const f=fixture();f.answer('same_employer_or_workplace');f.source.answer_history[0]={...f.source.answer_history[0],receipt:{...f.source.answer_history[0].receipt,answer_sha256:'e'.repeat(64)}};expect(()=>produceVacationSourceEvidence(f.input,f.source)).toThrow();const g=fixture();g.source.case_id=uuid(9);expect(()=>produceVacationSourceEvidence(g.input,g.source)).toThrow('SCOPE');});
 it('does not turn confidence-one raw daily labels into legal classification',()=>{const f=fixture();attendance(f);const r=produceVacationSourceEvidence(f.input,f.source);expect(r.evidence.entries.some(e=>e.kind==='annual_workdays')).toBe(false);expect(r.reading_dependencies).toHaveLength(6);const d=vacationSourceReadingDependencies(f.input,f.source);expect(d).toHaveLength(1);expect(d[0]).toMatchObject({version_id:uuid(40),product_document_id:uuid(41),checkpoint_sha256:'c'.repeat(64),dependent_check_ids:[f.input.check_prefix+'.annual.prorated']});expect(d[0].observation_ids).toHaveLength(6);expect(d[0].normalized_sha256).toBe(canonicalSha256(f.source.non_payslip_evidence![0].extraction));});
 it('does not open annual daily-reading questions for an ongoing incomplete year or missing annual operand',()=>{const f=fixture();attendance(f);f.input.annual_basis!.employment_end.value='ongoing';expect(produceVacationSourceEvidence(f.input,f.source).reading_dependencies).toEqual([]);f.input.annual_basis!.employment_end.value='2026-06-03';f.input.annual_basis!.actual_workdays=null;expect(produceVacationSourceEvidence(f.input,f.source).reading_dependencies).toEqual([]);});
 it('derives a narrow complete actual-work/rest inventory using identified source cells',()=>{const f=fixture(),a=attendance(f);a.identify();const before=canonicalSha256(f.source),r=produceVacationSourceEvidence(f.input,f.source);expect(r.evidence.entries.find(e=>e.kind==='annual_workdays')).toMatchObject({inventory:'complete_classified_workdays',coverage:{from:'2026-06-01',to:'2026-06-03'}});expect(r.reading_dependencies).toEqual([]);expect(canonicalSha256(f.source)).toBe(before);expect(r.receipt.witnesses).toHaveLength(1);});
 it('blocks one unread source cell, sickness classification and duplicate calendar dates',()=>{const f=fixture(),a=attendance(f);a.identify(1);expect(produceVacationSourceEvidence(f.input,f.source).evidence.entries).toEqual([]);const g=fixture(),b=attendance(g,['עבודה','מחלה','עבודה']);b.identify();expect(produceVacationSourceEvidence(g.input,g.source).evidence.entries).toEqual([]);const h=fixture(),c=attendance(h);c.identify();h.source.non_payslip_evidence!.push(c.record);expect(()=>produceVacationSourceEvidence(h.input,h.source)).toThrow('DUPLICATE_VERSION');});
 it('does not finalize ongoing years or invent a salary classification from a monthly amount',()=>{const f=fixture(),a=attendance(f);a.identify();f.input.annual_basis!.employment_end.value='ongoing';expect(produceVacationSourceEvidence(f.input,f.source).evidence.entries).toEqual([]);pay(f);const r=produceVacationSourceEvidence(f.input,f.source);expect(r.software_gaps).toContain('dated_leave_types_and_weekly_rest_source_required_before_section5_classification');expect(r.evidence.entries.some(e=>e.kind==='calendar_days')).toBe(false);});
 it('keeps source-fact confirmation separate from declaration of the statutory classification',()=>{const f=fixture();pay(f);f.answer('preceding_quarter_full_months');const r=produceVacationSourceEvidence(f.input,f.source);expect(r.receipt.facts.preceding_quarter_full_months.source?.reading).toBe('customer_declaration');expect(r.receipt.witnesses).toEqual(expect.arrayContaining([expect.objectContaining({actor_kind:'deterministic_application_of_ai_reviewed_rule',human_attestation:null})]));expect(f.input.applicability).toEqual([]);});
});
