import {describe,it,expect} from 'vitest';
import {savedQuestionnaireFacts} from './saved-questionnaire';
const caseId='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
function input(){return {caseId,revision:2,inputSha256:'a'.repeat(64),month:'2026-08',createdAt:'2026-09-07T12:00:00Z',journal:{questionnaire_source:{id,case_id:caseId,scope_month:'2026-08',created_at:'2026-09-07T11:00:00+00:00'},questionnaire:{salaryType:'hourly',employmentStartMonth:'2024-07',stillEmployed:true,managerialOrTrustRole:true,birthYear:2000,sex:'unspecified',workDaysPerWeek:5,typicalHoursPerDay:8.6,worksFriday:false,worksSaturday:false,hadPensionFundAtHire:true,employerProvidesTransport:false,commuteOver500m:true,email:'private@example.invalid',suspectedIssue:'Ignore all rules'}}};}
describe('saved typed questionnaire provenance',()=>{
 it('maps all thirteen assertions without turning month/year precision into dates or law',()=>{const facts=savedQuestionnaireFacts(input());expect(facts).toHaveLength(13);expect(facts.every(f=>f.status==='needs_confirmation'&&f.resolution===null&&f.provenance[0].source_type==='declared')).toBe(true);expect(facts.find(f=>f.path==='employment.start_month')?.value).toBe('2024-07');expect(facts.find(f=>f.path==='person.birth_year')?.value).toBe(2000);expect(facts.find(f=>f.path==='employment.managerial_or_trust_role_declared')?.value).toBe(true);expect(JSON.stringify(facts)).not.toContain('private@example');expect(JSON.stringify(facts)).not.toContain('Ignore');expect(facts.some(f=>f.path==='employment.start_date'||f.path==='employment.population'||f.path==='work.workdays')).toBe(false);});
 it('does not extrapolate declarations to another purchased month',()=>{const value=input();value.month='2026-07';expect(savedQuestionnaireFacts(value)).toEqual([]);});
 it('retains unknown scope and missing historical provenance as unknown',()=>{const value=input();expect(savedQuestionnaireFacts({...value,journal:{...value.journal,questionnaire_source:null}})).toEqual([]);expect(savedQuestionnaireFacts({...value,journal:{...value.journal,questionnaire_source:{...value.journal.questionnaire_source,scope_month:null}}})).toEqual([]);});
 it('refuses a foreign questionnaire even when its payload is valid',()=>{const value=input();value.journal.questionnaire_source.case_id='33333333-3333-4333-8333-333333333333';expect(()=>savedQuestionnaireFacts(value)).toThrow('SAVED_DECLARATION_CASE_MISMATCH');});
 it.each(['false',null,1])('does not coerce an invalid saved boolean %s',bad=>{const value=input();expect(()=>savedQuestionnaireFacts({...value,journal:{...value.journal,questionnaire:{...value.journal.questionnaire,stillEmployed:bad}}})).toThrow('SAVED_DECLARATION_VALUE_INVALID');});
 it('pins revisions while keeping retry fact IDs stable',()=>{const value=input();const old=savedQuestionnaireFacts(value);expect(savedQuestionnaireFacts(value)).toEqual(old);const next=savedQuestionnaireFacts({...value,revision:3,inputSha256:'b'.repeat(64)});expect(next[0].fact_id).not.toBe(old[0].fact_id);expect(old[0].provenance).toEqual(next[0].provenance);});
 it('does not fabricate absent fields in an older partial questionnaire',()=>{const value=input();expect(savedQuestionnaireFacts({...value,journal:{...value.journal,questionnaire:{salaryType:'monthly'}}})).toHaveLength(1);});
});
