import {describe,it,expect} from 'vitest';
import {canonicalSha256} from '../../rule-runtime/canonical.ts';
import {pensionEntitlementInputSchema,type PensionEntitlementInput} from './contracts.ts';
import {pensionProductFacts,pensionProductFactQuestions,pensionProductAge,evaluatePensionCaseRecipe,materializePensionCaseFacts,assertPensionDerivedFacts,pensionCaseConsumed,replayPensionProductFacts} from './product-facts.ts';
import {documentReviewInputSchema} from '../../document-review/contracts.ts';
import {documentReviewCalculationInputSchema} from '../../document-review/calculations.ts';
import {PENSION_SOURCE_REVIEW_SHA256} from './sources.ts';
import {resolvePensionEntitlement} from './index.ts';
import {pensionRecordedFixture} from './recorded-fixture.ts';
import {AI_RELEASE_DECISION_RECIPES} from '../../ai-release-decisions/catalog.ts';

const sha='a'.repeat(64),source={document_id:'synthetic-answer',version_id:'synthetic-answer-v1',file_sha256:sha,page:1,locator:'Synthetic authenticated answer snapshot',label:'Synthetic answer',reading:'customer_declaration' as const,reading_receipt_sha256:sha};
function fixture():PensionEntitlementInput{
 const known=(value:unknown)=>({state:'known',value,source,basis:'customer_declaration'}),missing={state:'missing',value:null,source:null,basis:'ai_source_assessment'};
 const p=pensionProductFacts();p.birth_date={state:'declared',value:'1990-06-15',source};p.employment_relationship={state:'declared',value:'employee',source};p.workplace_sector={state:'declared',value:'private',source};
 return pensionEntitlementInputSchema.parse({schema_version:'pension-entitlement-input-v1',catalog_id:'il.review.pension.general.2026',catalog_version:'1.0.0',case_id:'synthetic-case',run_id:'synthetic-run',check_prefix:'synthetic.pension',period:{from:'2026-06-01',to:'2026-06-30'},evaluated_at:'2026-09-12T00:00:00Z',
 source_manifest:[{document_id:source.document_id,version_id:source.version_id,file_sha256:sha,page_count:1,kind:'customer_answer',case_id:'synthetic-case'}],product_facts:p,
 facts:{employment_start:known('2020-01-01'),employment_end:known('ongoing'),continuous_employment:known(true),prior_coverage_at_start:missing,aged_21_or_more:missing,under_60:missing},
 pensionable_wage:null,eligible_interval_wage:null,applicability:[],recorded:[],remittance_status:'missing'});
}
function bind(input:PensionEntitlementInput){const recipe=AI_RELEASE_DECISION_RECIPES.find(r=>r.recipe_id==='ai-case.pension.general_coverage');if(!recipe)throw Error('Synthetic test requires the compiled pension case recipe');
 const body={schema_version:'pension-case-recipe-binding-v1',method:{recipe_id:recipe.recipe_id,recipe_version:recipe.recipe_version,recipe_sha256:recipe.recipe_sha256,source_policy_sha256:PENSION_SOURCE_REVIEW_SHA256,
 interpretation_receipt_sha256:sha,source_receipts:recipe.legal_sources.map(s=>({receipt_sha256:sha,source_version_id:s.version_id,artifact_sha256:s.file_sha256})),issued_at:'2026-09-11T00:00:00Z',expires_at:'2026-09-13T00:00:00Z'},evaluated_at:input.evaluated_at};
 return pensionEntitlementInputSchema.parse({...input,case_recipe_bindings:[{...body,binding_sha256:canonicalSha256(body)}]});}
describe('pension product facts and replayable factual recipe readiness',()=>{
 it('preserves historical packet shape and does not add unanswered facts by parsing',()=>{const i=fixture();delete i.product_facts;expect(pensionEntitlementInputSchema.parse(i)).toEqual(i);expect(pensionProductFactQuestions(i)).toEqual([]);});
 it('does not ask birthday or old employment questions again when sources are usable',()=>{const i=fixture();const paths=pensionProductFactQuestions(i).map(q=>q.path);expect(paths).not.toContain('product_facts.birth_date');expect(paths.every(p=>p.startsWith('product_facts.'))).toBe(true);expect(paths).not.toContain('facts.prior_coverage_at_start');});
 it.each(['missing','unknown','conflict','stale','expired','unreadable'] as const)('preserves %s birthday and does not derive age',state=>{const i=bind(fixture());i.product_facts!.birth_date={state,value:null,source:null};expect(evaluatePensionCaseRecipe('pension.general_coverage',i)).toMatchObject({allowed:false,reason:'birth_date_missing'});expect(materializePensionCaseFacts(i).facts.aged_21_or_more.state).toBe('missing');});
 it('derives exact age gates with binding, inputs and source proof without modifying original or accepting legal decisions',()=>{const i=bind(fixture()),before=canonicalSha256(i),effective=materializePensionCaseFacts(i);
  expect(canonicalSha256(i)).toBe(before);expect(effective.applicability).toEqual([]);expect(effective.facts.aged_21_or_more).toMatchObject({state:'derived',value:true,basis:'ai_source_assessment',source:{reading:'source_research'}});
  expect(effective.facts.aged_21_or_more.derivation?.inputs_sha256).toBe(canonicalSha256(pensionCaseConsumed(i,evaluatePensionCaseRecipe('pension.general_coverage',i).consumed_paths)));
  expect(()=>assertPensionDerivedFacts(effective)).not.toThrow();expect(resolvePensionEntitlement(effective).gaps.some(g=>g.dependency_id==='pension.pensionable_wage')).toBe(true);
 });
 it('rejects changed birthday, derived value, receipt and foreign manifest on replay',()=>{const i=materializePensionCaseFacts(bind(fixture()));
  for(const mutate of [(j:PensionEntitlementInput)=>{j.product_facts!.birth_date.value='1991-01-01';},(j:PensionEntitlementInput)=>{j.facts.aged_21_or_more.value=false;},(j:PensionEntitlementInput)=>{j.facts.under_60.derivation!.inputs_sha256='b'.repeat(64);},(j:PensionEntitlementInput)=>{j.source_manifest[0].case_id='foreign-case';}]){const j=structuredClone(i);mutate(j);expect(()=>assertPensionDerivedFacts(j)).toThrow();}
 });
 it('rejects duplicate, expired, wrong-policy and corrupt bindings',()=>{for(const kind of ['duplicate','expired','policy','hash']){const i=bind(fixture()),b=i.case_recipe_bindings![0];if(kind==='duplicate')i.case_recipe_bindings!.push(b);else if(kind==='expired')b.method.expires_at=i.evaluated_at;else if(kind==='policy')b.method.source_policy_sha256=sha;else b.binding_sha256='b'.repeat(64);
   if(kind==='expired'||kind==='policy'){const {binding_sha256,...body}=b;void binding_sha256;b.binding_sha256=canonicalSha256(body);}expect(()=>materializePensionCaseFacts(i)).toThrow();}});
 it('keeps the method assessment anchor distinct from earlier source extraction time',()=>{const i=bind(fixture());i.evaluated_at='2026-09-10T00:00:00Z';const effective=materializePensionCaseFacts(i);expect(effective.evaluated_at).toBe(i.evaluated_at);expect(effective.facts.aged_21_or_more.state).toBe('derived');expect(()=>assertPensionDerivedFacts(effective)).not.toThrow();});
 it('rejects a rehashed but fabricated method or source receipt',()=>{for(const field of ['recipe_sha256','source_receipts'] as const){const i=bind(fixture()),b=i.case_recipe_bindings![0];if(field==='recipe_sha256')b.method.recipe_sha256=sha;else b.method.source_receipts[0].artifact_sha256=sha;const {binding_sha256,...body}=b;void binding_sha256;b.binding_sha256=canonicalSha256(body);expect(()=>materializePensionCaseFacts(i)).toThrow('PENSION_CASE_BINDING_SCOPE');}});
 it('retires only its own accepted decision when a corrected factual answer becomes unknown',()=>{const i=bind(fixture()),m=i.case_recipe_bindings![0].method;
  const own={decision_id:'pension.general_coverage',state:'accepted' as const,basis:'ai_source_assessment' as const,explanation:JSON.stringify({schema_version:'ai-release-method-basis-v1',recipe_id:m.recipe_id,recipe_sha256:m.recipe_sha256,interpretation_receipt_sha256:m.interpretation_receipt_sha256}),sources:[],valid_until:m.expires_at};
  i.applicability=[own,{...own,decision_id:'pension.no_better_arrangement',explanation:'Separate source assessment'}];const effective=materializePensionCaseFacts(i);effective.product_facts!.workplace_sector={state:'unknown',value:null,source:null};
  const review=documentReviewInputSchema.parse({schema_version:'document-review-product-v1',case_id:i.case_id,period:i.period,purchased_scope:{order_id:'synthetic-order',receipt_sha256:sha,origin:'saved_order',topics:['pension']},documents:[{document_id:source.document_id,version_id:source.version_id,file_sha256:sha,reading_sha256:sha,case_id:i.case_id,kind:'other',period:i.period,page_count:1,label:'Synthetic source inventory',reading_origin:'source_inventory'}],checks:[],completion_input:{schema_version:'review-completion-input-v1',needs:[]},answer_bindings:[],answer_history:[],coverage_gaps:[]});
  const replay=replayPensionProductFacts(effective,i,review);expect(replay.facts.aged_21_or_more.state).toBe('missing');expect(replay.applicability[0].state).toBe('stale');expect(replay.applicability[1]).toEqual(i.applicability[1]);expect(i.applicability[0].state).toBe('accepted');
 });
 it('invalidates the old acceptance when a corrected birthday remains within the supported age range',()=>{const i=bind(fixture()),m=i.case_recipe_bindings![0].method;
  i.applicability=[{decision_id:'pension.general_coverage',state:'accepted',basis:'ai_source_assessment',sources:[],valid_until:m.expires_at,explanation:JSON.stringify({schema_version:'ai-release-method-basis-v1',recipe_id:m.recipe_id,recipe_sha256:m.recipe_sha256,interpretation_receipt_sha256:m.interpretation_receipt_sha256,consumed_sha256:canonicalSha256(pensionCaseConsumed(i,evaluatePensionCaseRecipe('pension.general_coverage',i).consumed_paths))})}];
  expect(materializePensionCaseFacts(i).applicability[0].state).toBe('accepted');i.product_facts!.birth_date.value='1991-06-15';const result=materializePensionCaseFacts(i);expect(result.facts.aged_21_or_more.value).toBe(true);expect(result.applicability[0].state).toBe('stale');expect(i.applicability[0].state).toBe('accepted');
 });
 it('cites factual recipe sources in generated candidate evidence while raw applicability remains law-only',()=>{const r=pensionRecordedFixture('300.00'),i=fixture();i.case_id=r.case_id;for(const s of i.source_manifest)s.case_id=r.case_id;i.source_manifest.push(...r.source_manifest);if(r.operation.kind!=='observed_ratio')throw Error('synthetic ratio');const denominator=r.operation.denominator_ref;i.pensionable_wage=structuredClone(r.operands.find(o=>o.id===denominator)!);
  const raw=bind(i),m=raw.case_recipe_bindings![0].method;raw.applicability=[{decision_id:'pension.general_coverage',state:'accepted',basis:'ai_source_assessment',sources:[],valid_until:m.expires_at,explanation:JSON.stringify({schema_version:'ai-release-method-basis-v1',recipe_id:m.recipe_id,recipe_sha256:m.recipe_sha256,interpretation_receipt_sha256:m.interpretation_receipt_sha256,consumed_sha256:canonicalSha256(pensionCaseConsumed(raw,evaluatePensionCaseRecipe('pension.general_coverage',raw).consumed_paths))})}];
  const effective=materializePensionCaseFacts(raw),checks=resolvePensionEntitlement(effective).checks;expect(checks).toHaveLength(3);const op=documentReviewCalculationInputSchema.parse(checks[0].calculation).operation;if(op.kind!=='candidate_rule')throw Error('synthetic candidate');expect(op.decisions.find(d=>d.decision_id==='pension.general_coverage')?.sources).toContainEqual(source);expect(raw.applicability[0].sources).toEqual([]);
 });
 it('uses report boundary birthdays, including an under-60 birthday inside the month',()=>{const i=fixture();i.product_facts!.birth_date.value='2005-06-01';expect(pensionProductAge(i)).toMatchObject({aged_21_or_more:true});i.product_facts!.birth_date.value='2005-06-02';expect(pensionProductAge(i)).toMatchObject({aged_21_or_more:false});i.product_facts!.birth_date.value='1966-06-30';expect(pensionProductAge(i)).toMatchObject({under_60:false});i.product_facts!.birth_date.value='1966-07-01';expect(pensionProductAge(i)).toMatchObject({under_60:true});});
 it('preserves existing age evidence and blocks a conflicting birthday',()=>{const i=fixture();for(const key of ['aged_21_or_more','under_60'] as const)i.facts[key]={state:'known',value:true,source,basis:'customer_declaration'};
  i.product_facts!.birth_date.value='2010-01-01';expect(evaluatePensionCaseRecipe('pension.general_coverage',i)).toMatchObject({allowed:false,reason:'age_source_conflict'});
  i.product_facts!.birth_date={state:'missing',value:null,source:null};expect(evaluatePensionCaseRecipe('pension.general_coverage',i)).toMatchObject({allowed:true});expect(pensionProductFactQuestions(i).some(q=>q.path==='product_facts.birth_date')).toBe(false);
 });
 it('does not turn known lack of other terms or a printed insured wage into legal classification',()=>{const i=fixture();i.product_facts!.other_pension_terms_known={state:'declared',value:false,source};expect(evaluatePensionCaseRecipe('pension.no_better_arrangement',i)).toMatchObject({allowed:false,reason:'arrangement_source_scope_missing'});expect(evaluatePensionCaseRecipe('pension.pensionable_wage',i)).toMatchObject({allowed:false,reason:'wage_component_classification_source_missing'});});
 it('accepts the existing exact identified fund relationship, asks no second fund question and keeps contradictory product answers blocked',()=>{const r=pensionRecordedFixture('300.00'),i=fixture();i.case_id=r.case_id;for(const m of i.source_manifest)m.case_id=r.case_id;i.source_manifest.push(...r.source_manifest);i.recorded=[{share:'employee',relationship_check:r}];
  expect(evaluatePensionCaseRecipe('pension.pension_fund',i)).toMatchObject({allowed:true,consumed_paths:['period','recorded.0.relationship_check']});expect(pensionProductFactQuestions(i).some(q=>q.path==='product_facts.pension_product')).toBe(false);
  i.product_facts!.pension_product={state:'declared',value:'insurance_policy',source};expect(evaluatePensionCaseRecipe('pension.pension_fund',i)).toMatchObject({allowed:false,reason:'pension_product_conflict_or_unsupported'});
 });
 it('keeps unconfirmed fund relationships and a plain customer product declaration insufficient',()=>{const i=fixture();i.product_facts!.pension_product={state:'declared',value:'pension_fund',source};expect(evaluatePensionCaseRecipe('pension.pension_fund',i)).toMatchObject({allowed:false,reason:'identified_fund_source_missing'});});
 it('rejects observed declarations, foreign period, malformed sources and source changes',()=>{const i=fixture();i.product_facts!.birth_date.state='observed';expect(()=>evaluatePensionCaseRecipe('pension.general_coverage',i)).toThrow('PENSION_PRODUCT_FACT_BASIS');i.product_facts!.birth_date.state='declared';i.product_facts!.birth_date.source={...source,file_sha256:'b'.repeat(64)};expect(()=>evaluatePensionCaseRecipe('pension.general_coverage',i)).toThrow('PENSION_PRODUCT_SOURCE_BINDING');});
});
