// Synthetic test support only. No provider calls, persisted findings, or legal approvals.
import {randomUUID} from 'node:crypto';
import {buildSyntheticCaseFixture} from '../../case-analysis/synthetic-fixtures.ts';
import {canonicalSha256} from '../../rule-runtime/canonical.ts';
import {normalizedPayslipExtractionSchema} from '../../extraction/payslip.ts';
import {documentSourceStructureTarget,resolveDocumentSourceStructureVerification,materializeDocumentSourceStructureVerification} from '../../../server/product/reports/document-source-structure.ts';
import {reviewInputFromPayslips,PAYSLIP_SOURCE_STRUCTURE_POLICY} from '../../document-review/payslip-adapter.ts';
import {documentReviewCalculationInputSchema} from '../../document-review/calculations.ts';
export function pensionRecordedFixture(amount:string,confirmed=true,combined=false){
 const f=buildSyntheticCaseFixture({fixture_id:'synthetic-pension-recorded-'+randomUUID(),mode:'real'}),d={...f.stored.documents[0],document_period:{start_date:'2026-06-01',end_date:'2026-06-30'}},template=f.stored.extractions[0];
 const source={document_id:d.document_id,page:1,text_fragment:'Synthetic explicitly labelled pension employee and base June 2026',source_scope:{period_kind:'current',fund_kind:'pension',column_label:'current month'}},base=randomUUID(),employee=randomUUID();
 const field=(field:string,candidate_id:string,raw_value:string,normalized_value:unknown)=>({candidate_id,field,raw_value,normalized_value,confidence:1,source,extraction_method:'fixture',warning_flags:[]});
 const machine=normalizedPayslipExtractionSchema.parse({...template,document_quality_confidence:1,fields:[field('salary_period',randomUUID(),'06/2026',{year:2026,month:6,start_date:'2026-06-01',end_date:'2026-06-30'}),field('pension_base',base,'5000.00',{currency:'ILS',minor_units:500000}),...(!combined?[field('pension_employee_contribution',employee,amount,{currency:'ILS',minor_units:Number(amount)*100})]:[])],additional_components:[],source_scope_observations:combined?[{scope:'combined_employer_funds',source_label:'Synthetic combined employer contribution',policy_version:'payslip-explicit-source-scope-v1',candidate:{candidate_id:employee,field:'pension_employer_contribution',raw_value:amount,confidence:1,source:{...source,source_scope:{period_kind:'current',fund_kind:'combined',column_label:'combined employer'}},extraction_method:'fixture',warning_flags:[]}}]:[]});
 if(combined)machine.fields=machine.fields.map(f=>f.candidate_id===base?{...f,source:{...f.source,source_scope:{period_kind:'current',fund_kind:'combined',column_label:'combined employer base'}}}:f);
 const first=normalizedPayslipExtractionSchema.parse(machine),result={final_extraction:machine,first_pass:{normalized_extraction:first}};
 const checkpoint={schema_version:'tivdoc-saved-extraction-v1',case_id:d.case_id,product_document_id:randomUUID(),version_id:d.document_id,input_sha256:d.content_sha256,expected_month:'2026-06',period_mismatch:false,result_sha256:canonicalSha256(result),run:{result}};
 const target=documentSourceStructureTarget({checkpoint,policyVersion:'synthetic-pension-v1',selector:{kind:'source_relationship',componentKind:combined?'combined_employer_funds':'pension_employee',contribution:{kind:combined?'scope':'field',id:employee},base:{kind:'field',id:base}}});
 const decision=resolveDocumentSourceStructureVerification({target,currentCheckpoint:checkpoint,policyVersion:'synthetic-pension-v1',caseId:d.case_id,month:'2026-06',requestId:randomUUID(),answerRevision:1,identityId:randomUUID(),answeredAt:'2026-09-12T00:00:00Z',answer:{schema_version:'document-field-answer-v3',action:'correct',structured_value:{kind:'source_relationship',component_kind:combined?'combined_employer_funds':'pension_employee',fund_kind:combined?'combined':'pension',fund_label:'Synthetic pension fund',source_kind:'same_row',relationship:'same_base',basis:{page:1,locator:'Synthetic row A',text:'Synthetic contribution and base explicitly linked'}}}});
 const reading=materializeDocumentSourceStructureVerification(decision,canonicalSha256(machine));if(!reading)throw Error('synthetic reading missing');
 const extraction=normalizedPayslipExtractionSchema.parse({...machine,...(confirmed?{customer_source_structures:[reading.reading],source_reading_context:{checkpoint_result_sha256:checkpoint.result_sha256,first_pass:first}}:{})});
 const review=reviewInputFromPayslips({case_id:d.case_id,period:{from:'2026-06-01',to:'2026-06-30'},review_policy:PAYSLIP_SOURCE_STRUCTURE_POLICY,purchased_scope:{order_id:'synthetic-pension-order',receipt_sha256:'a'.repeat(64),origin:'saved_order',topics:['pension']},snapshot:{...f.stored,documents:[d],extractions:[extraction]},retained_unresolved_fields:[{case_id:d.case_id,document_id:d.document_id,source_sha256:d.content_sha256,checkpoint_result_sha256:checkpoint.result_sha256,checkpoint_result:result,final_extraction_sha256:canonicalSha256(machine),first_pass:first}]});
 const check=review.checks.find(c=>c.check_id.endsWith(combined?'ratio.combined_employer_funds':'ratio.pension_employee_contribution'));if(!check)throw Error('synthetic ratio absent');return documentReviewCalculationInputSchema.parse(check.calculation);
}
