"use client";
import {useRef,useState} from 'react';
import type {SupportQueueItem} from '@/server/product/reports/support';
export function SupportPanel({csrfToken}:{csrfToken:string}){
 const [items,setItems]=useState<SupportQueueItem[]>([]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){setBusy(true);try{const r=await fetch('/api/operations/report-qa/support',{cache:'no-store'});if(!r.ok)throw new Error();setItems((await r.json()).data);setLoaded(true);setNotice('התור נטען.');}catch{setNotice('תור התמיכה אינו זמין בהרשאה הנוכחית.');}finally{setBusy(false);}}
 return <section><h2>תמיכת בעלים</h2><p>יעד פנימי למענה: שני ימי עסקים. המענה אינו בדיקה מקצועית או אישור פרסום דוח. מוצגות עד 100 הפניות הפתוחות הראשונות.</p><button disabled={busy} onClick={load}>טעינת פניות תמיכה</button><p role="status">{notice}</p>{loaded&&items.length===0?<p>אין פניות פתוחות.</p>:null}{items.map(t=><SupportItem key={`${t.id}:${t.revision}`} item={t} csrfToken={csrfToken} onSaved={load}/>)}</section>;
}
function SupportItem({item,csrfToken,onSaved}:{item:SupportQueueItem;csrfToken:string;onSaved:()=>void}){
 const [message,setMessage]=useState(''),[state,setState]=useState<'waiting_customer'|'resolved'>('waiting_customer'),[priority,setPriority]=useState(item.priority),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const retry=useRef<{key:string;id:string}|null>(null);
 async function send(){setBusy(true);const key=JSON.stringify({message,state,priority});if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};try{const r=await fetch('/api/operations/report-qa/support',{method:'POST',headers:{'Content-Type':'application/json','x-tivdoc-csrf':csrfToken},body:JSON.stringify({id:retry.current.id,threadId:item.id,revision:item.revision,message,state,priority})});if(!r.ok)throw new Error();onSaved();}catch{setNotice('לא ניתן לאשר שהמענה נשמר. נסו שוב; אם הפנייה השתנתה, טענו את התור מחדש.');}finally{setBusy(false);}}
 return <article className="support-threads"><h3><bdi>{item.public_id}</bdi> · {item.origin==='finding'?'ממצא בדוח':'פנייה מהתיק'}{item.target_exceeded===null?' · חישוב יעד המענה אינו זמין':item.target_exceeded?' · עבר יעד המענה הפנימי':''}</h3><p>נפתחה: <time dateTime={item.created_at}>{new Intl.DateTimeFormat('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'short',timeStyle:'short'}).format(new Date(item.created_at))}</time> · מצב: {item.state}</p>{item.report_id?<p>מקור: דוח <bdi>{item.report_id}</bdi>, ממצא <bdi>{item.finding_id}</bdi></p>:null}<ol>{item.messages.map(m=><li key={m.id}><strong>{m.author_kind==='owner'?'תמיכה':'לקוח'}</strong><p>{m.message}</p></li>)}</ol><label>מענה לתיק<textarea rows={4} value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/></label><label>מצב אחרי המענה<select value={state} onChange={e=>setState(e.target.value as typeof state)}><option value="waiting_customer">ממתין ללקוח</option><option value="resolved">טופל</option></select></label><label>עדיפות<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="normal">רגילה</option><option value="urgent">דחופה</option></select></label><button disabled={busy||message.trim().length<4} onClick={send}>שמירת מענה בתיק</button><p role="status">{notice}</p></article>;
}
