-- P12: publication semantics and a declared case cohort; no client-supplied totals.
create table private.case_report_views(report_id uuid not null references public.case_report_projections(id) on delete cascade,identity_id uuid not null references public.case_identities(id) on delete cascade,opened_at timestamptz not null default now(),primary key(report_id,identity_id));
revoke all on private.case_report_views from public,anon,authenticated,service_role,tivdoc_web_runtime;
grant select on private.case_report_views to tivdoc_operations_runtime;
create function public.case_report_open(target_case uuid,target_identity uuid,target_report uuid) returns void language plpgsql security definer set search_path='' as $$
begin
 if not exists(select 1 from public.case_identity_cases where case_id=target_case and identity_id=target_identity) or not exists(select 1 from public.case_report_qa where case_id=target_case and projection_id=target_report and published_at is not null) then raise exception 'REPORT_FORBIDDEN';end if;
 insert into private.case_report_views(report_id,identity_id) values(target_report,target_identity) on conflict do nothing;
end;$$;
revoke all on function public.case_report_open(uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function public.case_report_open(uuid,uuid,uuid) to service_role,tivdoc_web_runtime;
create or replace function public.case_funnel_metrics(target_since timestamptz,target_until timestamptz) returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb;
begin
 if target_since is null or target_until is null or target_since>=target_until or target_until-target_since>interval '366 days' or target_until>now()+interval '1 minute' then raise exception 'METRICS_WINDOW_INVALID';end if;
 with cohort as (select id from public.cases where is_qa=false and created_at>=target_since and created_at<target_until),
 paid as (select distinct c.id from cohort c join public.payments p on p.case_id=c.id where p.status='verified' and p.verified_at<target_until),
 published as (select distinct on(p.id) p.id,p.case_id,p.projection,q.document_track,q.review_seconds,q.published_at from public.case_report_projections p join cohort c on c.id=p.case_id join public.case_report_qa q on q.projection_id=p.id where q.published_at is not null and q.published_at<target_until order by p.id,q.published_at),
 findings as (select p.case_id,min(p.published_at) first_published_at from published p join paid c on c.id=p.case_id where exists(select 1 from jsonb_array_elements(p.projection->'topics') t where t->>'gate'='checked' and t->>'status'='finding') group by p.case_id),
 measured as (select p.*,case when not exists(select 1 from jsonb_array_elements(p.projection->'topics') t where t->>'gate'='checked') then 'not_checked' when exists(select 1 from jsonb_array_elements(p.projection->'topics') t where t->>'gate'='checked' and t->>'status'='finding') then 'finding' else 'no_finding_in_checked_scope' end outcome from published p),
 events as (select 'case_created' event_name,count(*) cases from cohort union all select 'document_uploaded',count(distinct d.case_id) from public.documents d join cohort c on c.id=d.case_id where d.created_at<target_until union all select 'payment_verified',count(*) from paid union all select e.event_name,count(distinct e.session_id) from public.funnel_events e where e.event_name in ('landing_view','start_check') and e.created_at>=target_since and e.created_at<target_until and not exists(select 1 from public.funnel_events qa join public.cases c on c.id=qa.case_id where qa.session_id=e.session_id and c.is_qa) group by e.event_name)
 select jsonb_build_object('schema_version','tivdoc-metrics-v1','window',jsonb_build_object('since',target_since,'until',target_until,'cohort','non_qa_cases_created_in_window','anonymous_population','sessions_observed_in_window_known_qa_excluded'),'events',(select jsonb_agg(to_jsonb(e)) from events e),'counts',jsonb_build_object('reports',(select count(*) from published),'automatic_reports',(select count(*) from published where document_track='automatic'),'reviewed_reports',(select count(*) from published where document_track='human'),'review_seconds_total',(select coalesce(sum(review_seconds),0) from published where document_track='human'),'cases_reviewed',(select count(distinct case_id) from published where document_track='human' and review_seconds is not null),'cases_with_finding',(select count(*) from findings),'full_reports_purchased',(select count(distinct o.case_id) from private.product_orders o join findings f on f.case_id=o.case_id where o.kind='full' and o.state='paid' and o.verified_at>=f.first_published_at and o.verified_at<target_until)),'sample',jsonb_build_object('cases',(select count(*) from cohort),'paid_cases',(select count(*) from paid),'published_cases',(select count(distinct case_id) from published),'opened_cases',(select count(distinct p.case_id) from published p join private.case_report_views v on v.report_id=p.id where v.opened_at<target_until),'qa_cases_excluded',(select count(*) from public.cases where is_qa and created_at>=target_since and created_at<target_until),'review_duration_missing',(select count(*) from published where document_track='human' and review_seconds is null)),'outcome_dictionary','published-topic-semantics-v1','outcomes',(select coalesce(jsonb_object_agg(outcome,n),'{}'::jsonb) from (select outcome,count(*) n from measured group by outcome) o),'processing_cost_minor',null,'storage_integrity','not_measured') into result;
 return result;
end;$$;
revoke all on function public.case_funnel_metrics(timestamptz,timestamptz) from public,anon,authenticated,service_role,tivdoc_web_runtime;
grant execute on function public.case_funnel_metrics(timestamptz,timestamptz) to tivdoc_operations_runtime;
-- Definer reads explicit aggregate sources under FORCE RLS, never browser rights.
do $$ begin execute format('create policy metrics_owner_events on public.funnel_events for select to %I using(true)',current_user);end $$;
